"""Generate the site pages for images, prompts and scripts from their sources.

License: CC0-1.0 (public domain dedication,
https://creativecommons.org/publicdomain/zero/1.0/).

Standard library only, plus sitelib.py next to this file. No git call, no clock;
the repository is never derived from the current directory.

USAGE
    python3 -B scripts/site/sync.py [--root DIR] [--write] [--prune] [--check]

    (default)        print a plan (counts, then one line per create, update,
                     delete or stale path) and write nothing; exit 0
    --write          apply the plan
    --check          exit 1 on drift or stale files, 0 when clean
    --prune          with --write: also delete stale images and stale generated
                     pages; any other stale file is reported and never deleted.
                     Without --write it only reports what it would delete.
    --root DIR       repository root (default: two levels above this file)
    Exit 2: usage error (--check with --write or --prune), unreadable or invalid
    input. The message is "sync: <path>: <message>" on standard error.

PUBLIC API (frozen)
    compute_outputs(root: Path) -> dict[str, bytes]
        Keys are POSIX paths relative to root, in sorted order; values are the
        exact bytes to write (UTF-8, LF, one final newline for text). Raises
        InputError (issues: list of "path: message" strings) on invalid input.
    OWNED_DIRS   the folders this tool owns; a file there that compute_outputs
                 does not produce is stale.

SOURCES AND OUTPUTS
    images/**                          -> docs/assets/images/** (bytes copied)
    prompts/<code>/*.md                -> docs/prompts/<code>/<id>.md
    scripts/<code>/*.py, *.sh and
    scripts/common/*.py (stage OP)     -> docs/scripts/<code>/<id>.md
    plus docs/{prompts,scripts}/index.md always, and docs/<kind>/<code>/index.md
    for each stage that has at least one item.

CHOICES WHERE THE PLAN IS SILENT OR AMBIGUOUS
* IDs must read P-<code>-<nn> (prompts) or X-<code>-<nn> (scripts): nn has two
  digits (three only above 99), no sub-stage suffix. A prompt's `stage` and a
  script's optional `Stage` must equal the ID code; the ID code must match the
  folder (scripts/common counts as OP).
* Names of prompts and scripts use only letters, digits, ".", "_" and "-", since
  they reach a comment, a table cell and a URL. Dotfiles, README.md, names that
  start with "_" (and "test_" for scripts) are ignored.
* "Used in" ignores pages that are generated or that live inside OWNED_DIRS, so
  the outputs never depend on earlier outputs or on stale files. A page needs a
  non-empty string title to be listed. Pages are listed in path order; several
  pages are joined with ", ".
* An empty Needs or Placeholders cell reads "none". Optional Sub-stage, Inputs
  and Outputs rows are omitted when empty. kind and version are not shown.
  A script's Inputs and Outputs rows come after License.
* Index intros are fixed text. With no items the top-level index says so
  instead of showing an empty table.
* GENERATED comment on an index page names its source folder ("prompts/").
* A title may not contain "{{" or "{%" (it sits outside the raw block).
* A trailing "/" on source_repo_url is dropped before "/blob/".
* --prune deletes only image files under docs/assets/images and generated .md
  files. Emptied folders are removed only inside OWNED_DIRS, never the owned
  folder itself.
* Header and front matter text is plain text apart from backtick code spans.
  md_escape() backslash-escapes the backslash and the characters * _ [ ] < > |
  outside code spans in every metadata and index table cell (values and link
  text) and in every H1; fenced blocks and front matter are never escaped. In
  table cells a "|" inside a code span is escaped too, because it would split
  the cell. Newlines in a cell collapse to one space.
"""

import argparse
import posixpath
import re
import sys
import urllib.parse
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path

sys.dont_write_bytecode = True
if sys.version_info < (3, 10):
    print(
        "sync: this tool needs Python 3.10 or newer, but this is "
        f"{sys.version_info.major}.{sys.version_info.minor}. "
        "Run it with a newer python3.",
        file=sys.stderr,
    )
    sys.exit(2)
sys.path.insert(0, str(Path(__file__).resolve().parent))

import sitelib  # noqa: E402  # pylint: disable=wrong-import-position

OWNED_DIRS = ("docs/assets/images", "docs/prompts", "docs/scripts")
IMAGE_SUFFIXES = (".svg", ".png", ".jpg", ".jpeg", ".gif", ".webp")
GENERATED_MARK = "GENERATED by scripts/site/sync.py"

_SOURCE_NAME_RE = re.compile(r"[A-Za-z0-9._-]+")
_IMAGE_NAME_RE = re.compile(r"[a-z0-9._/-]+")
_ENDRAW_RE = re.compile(r"\{%-?\s*endraw")
_RUNS_RE = re.compile(r"`+")
_SPACE_AROUND_NEWLINE_RE = re.compile(r"\s*\n\s*")
_CODE_SPAN_RE = re.compile(r"(?<!`)(`+)(?!`).*?(?<!`)\1(?!`)", re.S)
_MD_SPECIAL_RE = re.compile(r"([\\*_\[\]<>|])")

Config = tuple[str, str]  # (source_repo_url, source_branch)


class InputError(Exception):
    """A source cannot be turned into pages; ``issues`` holds "path: message"."""

    def __init__(self, issues: Sequence[str]) -> None:
        super().__init__("; ".join(issues))
        self.issues = list(issues)


@dataclass(frozen=True)
class _Kind:
    name: str
    plural: str
    prefix: str
    library: str
    nav_order: int
    intro: tuple[str, str]


PROMPTS = _Kind(
    "prompt",
    "prompts",
    "P",
    "Prompt library",
    80,
    (
        "Every prompt in this library, in pipeline order. Each page shows the "
        "prompt text, what it needs, its placeholders, and the guide pages that "
        "use it.",
        "These pages are generated from the files in `prompts/`. Edit a source "
        "file and run `python3 scripts/site/sync.py --write`; never edit a page "
        "here by hand.",
    ),
)
SCRIPTS = _Kind(
    "script",
    "scripts",
    "X",
    "Script library",
    81,
    (
        "Every script in this library, in pipeline order. Each page shows what "
        "the script does, how to run it, and its full source code.",
        "These pages are generated from the files in `scripts/`. Edit a source "
        "file and run `python3 scripts/site/sync.py --write`; never edit a page "
        "here by hand.",
    ),
)


@dataclass
class Item:
    """One prompt or script, ready to be rendered."""

    kind: _Kind
    id: str
    code: str
    number: int
    title: str
    purpose: str
    source: str
    rows: list[tuple[str, str]]
    body: str
    lang: str = ""
    notes: str = ""

    @property
    def out(self) -> str:
        """Repo-relative POSIX path of the generated page."""
        return f"docs/{self.kind.plural}/{self.code.lower()}/{self.id.lower()}.md"


# ---- small helpers -----------------------------------------------------------
def _rel(root: Path, path: Path) -> str:
    return path.relative_to(root).as_posix()


def _why(exc: Exception) -> str:
    if isinstance(exc, UnicodeDecodeError):
        return "not valid UTF-8"
    if isinstance(exc, OSError):
        return f"cannot read ({exc.strerror or type(exc).__name__})"
    return str(exc)


def _read(root: Path, path: Path, errors: list[str]) -> str | None:
    try:
        return sitelib.read_text(path)
    except (OSError, UnicodeDecodeError) as exc:
        errors.append(f"{_rel(root, path)}: {_why(exc)}")
        return None


def _is_hidden(name: str) -> bool:
    return name.startswith(".")


def _direct_files(root: Path, folder: str, suffixes: Sequence[str]) -> list[Path]:
    """Files directly inside root/folder (no sub-folders), sorted."""
    return sitelib.walk_files(root, folder, suffixes, skip_dir=lambda _name: True)


def md_escape(text: str, table: bool = False) -> str:
    """Backslash-escape Markdown-significant characters outside code spans.

    Escaped: \\ * _ [ ] < > and |. Text between matching backtick runs (a code
    span) is left as it is, except that with table=True its "|" is escaped,
    since an unescaped pipe would split the table cell.
    """
    parts: list[str] = []
    last = 0
    for span in _CODE_SPAN_RE.finditer(text):
        parts.append(_MD_SPECIAL_RE.sub(r"\\\1", text[last : span.start()]))
        parts.append(span.group().replace("|", "\\|") if table else span.group())
        last = span.end()
    parts.append(_MD_SPECIAL_RE.sub(r"\\\1", text[last:]))
    return "".join(parts)


def _cell(text: str) -> str:
    """One escaped table cell value: newlines collapse to a space."""
    return md_escape(_SPACE_AROUND_NEWLINE_RE.sub(" ", text.strip()), table=True)


def _link(text: str, target: str) -> str:
    """A Markdown link for use inside a table cell; the text is escaped."""
    return f"[{md_escape(text, table=True)}]({target})"


def _heading(text: str) -> str:
    return f"# {md_escape(text)}"


def _fence(body: str) -> str:
    longest = max((len(run) for run in _RUNS_RE.findall(body)), default=0)
    return "`" * max(4, longest + 1)


def _yaml_value(value: str | int | bool) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _text(value: object) -> str:
    if isinstance(value, list):
        return ", ".join(str(part) for part in value)
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _table(header: Sequence[str], rows: Sequence[Sequence[str]]) -> list[str]:
    """Table lines; every cell must already be escaped (see _cell and _link)."""
    return [
        "| " + " | ".join(header) + " |",
        "|" + "---|" * len(header),
        *("| " + " | ".join(row) + " |" for row in rows),
    ]


def _title_problem(title: str) -> str:
    if "{{" in title or "{%" in title:
        return "title must not contain '{{' or '{%' (it sits outside the raw block)"
    return ""


def _id_number(item_id: str, prefix: str, code: str, folder: str) -> tuple[int, str]:
    """Return (number, "") for a valid ID, else (-1, message)."""
    split = sitelib.split_id(item_id)
    shape = f"ID {item_id!r} must look like {prefix}-<stage code>-<nn>, e.g. "
    shape += f"{prefix}-{code}-04"
    if split is None or split[0] != prefix or len(split[2]) != 1 or split[2][0][1]:
        return -1, shape
    number = split[2][0][0]
    if item_id != f"{prefix}-{split[1]}-{number:02d}":
        return -1, shape
    if split[1] != code:
        return -1, f"ID {item_id} has stage code {split[1]}, but {folder} is for {code}"
    return number, ""


# ---- collecting the sources ----------------------------------------------------
def _collect_images(root: Path, errors: list[str]) -> dict[str, bytes]:
    found: dict[str, bytes] = {}
    base = root / "images"
    for path in sitelib.walk_files(root, "images", None, skip_dir=_is_hidden):
        if _is_hidden(path.name) or path.suffix.lower() not in IMAGE_SUFFIXES:
            continue
        rel = path.relative_to(base).as_posix()
        if not _IMAGE_NAME_RE.fullmatch(rel):
            errors.append(
                f"images/{rel}: image names may use only a-z, 0-9, '.', '_', '-' "
                "and '/'"
            )
            continue
        try:
            found[f"docs/assets/images/{rel}"] = path.read_bytes()
        except OSError as exc:
            errors.append(f"images/{rel}: {_why(exc)}")
    return found


def _read_config(root: Path, errors: list[str]) -> Config | None:
    text = _read(root, root / "docs" / "_config.yml", errors)
    if text is None:
        return None
    values = []
    for key in ("source_repo_url", "source_branch"):
        value = sitelib.read_config_scalar(text, key)
        if not value:
            errors.append(f"docs/_config.yml: missing or empty key '{key}'")
        values.append(value or "")
    return (values[0], values[1]) if all(values) else None


def _source_files(
    root: Path, folder: str, suffixes: Sequence[str], skip_tests: bool
) -> list[Path]:
    """Candidate source files in one folder, minus ignored names."""
    skipped = ("_", ".", "test_") if skip_tests else ("_", ".")
    return [
        path
        for path in _direct_files(root, folder, suffixes)
        if not path.name.startswith(skipped) and path.name.lower() != "readme.md"
    ]


def _name_problem(rel: str, name: str, errors: list[str]) -> bool:
    if _SOURCE_NAME_RE.fullmatch(name):
        return False
    errors.append(f"{rel}: file names may use only letters, digits, '.', '_' and '-'")
    return True


def _prompt_item(root: Path, code: str, path: Path, errors: list[str]) -> Item | None:
    rel, folder = _rel(root, path), f"prompts/{code.lower()}"
    if _name_problem(rel, path.name, errors):
        return None
    try:
        doc = sitelib.parse_prompt(path)
    except (OSError, UnicodeDecodeError) as exc:
        errors.append(f"{rel}: {_why(exc)}")
        return None
    if doc.errors:
        errors.extend(f"{rel}: line {n}: {msg}" for n, msg in doc.errors)
        return None
    front, lines = doc.front, doc.key_lines
    number, problem = _id_number(front["id"], "P", code, folder)
    if number < 0:
        errors.append(f"{rel}: line {lines['id']}: {problem}")
        return None
    if front["stage"] != code:
        msg = f"stage {front['stage']!r} disagrees with the ID code and {folder}"
        errors.append(f"{rel}: line {lines['stage']}: {msg}")
        return None
    problem = _title_problem(front["title"])
    if problem:
        errors.append(f"{rel}: line {lines['title']}: {problem}")
        return None
    rows = [("Purpose", _cell(front["purpose"]))]
    for label, key in (
        ("Sub-stage", "sub_stage"),
        ("Inputs", "inputs"),
        ("Outputs", "outputs"),
    ):
        value = _text(front[key]).strip() if key in front else ""
        if value:
            rows.append((label, _cell(value)))
    needs = ", ".join(f"`{name}`" for name in front["capabilities"])
    names = dict.fromkeys(front["placeholders"])
    holders = ", ".join("`{{" + name + "}}`" for name in names)
    rows += [
        ("Needs", _cell(needs or "none")),
        ("Placeholders", _cell(holders or "none")),
    ]
    return Item(
        PROMPTS,
        front["id"],
        code,
        number,
        front["title"].strip(),
        front["purpose"],
        rel,
        rows,
        doc.body,
        notes=doc.notes,
    )


def _collect_prompts(root: Path, errors: list[str]) -> list[Item]:
    items = []
    for code in sitelib.STAGES:
        for path in _source_files(root, f"prompts/{code.lower()}", (".md",), False):
            item = _prompt_item(root, code, path, errors)
            if item is not None:
                items.append(item)
    return items


def _script_item(
    root: Path, code: str, path: Path, common: list[str], errors: list[str]
) -> Item | None:
    rel = _rel(root, path)
    folder = posixpath.dirname(rel)
    if _name_problem(rel, path.name, errors):
        return None
    text = _read(root, path, errors)
    if text is None:
        return None
    endraw = _ENDRAW_RE.search(text)
    if endraw:
        line = text.count("\n", 0, endraw.start()) + 1
        msg = "'{% endraw' would end the generated raw block"
        errors.append(f"{rel}: line {line}: {msg}")
        return None
    try:
        header = sitelib.parse_script_header(path, common)
    except (OSError, UnicodeDecodeError) as exc:
        errors.append(f"{rel}: {_why(exc)}")
        return None
    if header.errors:
        errors.extend(f"{rel}: line {n}: {msg}" for n, msg in header.errors)
        return None
    fields, lines = header.fields, header.key_lines
    number, problem = _id_number(fields["ID"], "X", code, folder)
    if number < 0:
        errors.append(f"{rel}: line {lines['ID']}: {problem}")
        return None
    if fields.get("Stage", code) != code:
        msg = f"Stage {fields['Stage']!r} disagrees with the ID code and {folder}"
        errors.append(f"{rel}: line {lines['Stage']}: {msg}")
        return None
    title = fields.get("Title", "").strip() or path.stem.replace("_", " ")
    problem = _title_problem(title)
    if problem:
        errors.append(f"{rel}: line {lines.get('Title', 1)}: {problem}")
        return None
    labels = ("Purpose", "Usage", "Dependencies", "Writes files", "License")
    rows = [(label, _cell(fields[label])) for label in labels]
    rows += [
        (label, _cell(fields[label]))
        for label in ("Inputs", "Outputs")
        if fields.get(label, "").strip()
    ]
    lang = "python" if path.suffix == ".py" else "bash"
    body = text.removesuffix("\n")
    return Item(
        SCRIPTS,
        fields["ID"],
        code,
        number,
        title,
        fields["Purpose"],
        rel,
        rows,
        body,
        lang,
    )


def _collect_scripts(root: Path, errors: list[str]) -> list[Item]:
    common = sitelib.common_modules(root)
    sources = [
        (code, path)
        for code in sitelib.STAGES
        for path in _source_files(root, f"scripts/{code.lower()}", (".py", ".sh"), True)
    ]
    sources += [
        ("OP", path) for path in _source_files(root, "scripts/common", (".py",), True)
    ]
    items = []
    for code, path in sources:
        item = _script_item(root, code, path, common, errors)
        if item is not None:
            items.append(item)
    return items


def _unique(items: list[Item], errors: list[str]) -> list[Item]:
    seen: dict[str, str] = {}
    kept = []
    for item in items:
        if item.id in seen:
            errors.append(
                f"{item.source}: duplicate ID {item.id} (also in {seen[item.id]})"
            )
        else:
            seen[item.id] = item.source
            kept.append(item)
    return kept


def _doc_pages(root: Path, errors: list[str]) -> list[sitelib.Page]:
    try:
        return sitelib.load_pages(root)
    except (OSError, UnicodeDecodeError):
        before = len(errors)
        for path in sitelib.walk_files(root, "docs", (".md",)):
            _read(root, path, errors)
        if len(errors) == before:
            errors.append("docs: a page could not be read")
        return []


def _references(
    pages: Sequence[sitelib.Page], key: str
) -> dict[str, list[sitelib.Page]]:
    """Map item ID to the hand-written pages that list it under `key`."""
    refs: dict[str, list[sitelib.Page]] = {}
    for page in pages:
        title = page.front.get("title")
        listed = page.front.get(key)
        if (
            page.front.get("generated") is True
            or any(page.rel.startswith(owned + "/") for owned in OWNED_DIRS)
            or not isinstance(title, str)
            or not title.strip()
            or not isinstance(listed, list)
        ):
            continue
        for item_id in dict.fromkeys(listed):
            refs.setdefault(item_id, []).append(page)
    return refs


# ---- rendering -----------------------------------------------------------------
def _page(
    front: Sequence[tuple[str, str | int | bool]],
    source: str,
    body: Sequence[str],
) -> bytes:
    lines = [
        "---",
        *(f"{key}: {_yaml_value(value)}" for key, value in front),
        "---",
        f"<!-- {GENERATED_MARK} from {source}. Do not edit. -->",
        "{% raw %}",
        "",
        *body,
        "{% endraw %}",
    ]
    return ("\n".join(lines) + "\n").encode("utf-8")


def _page_link(page: sitelib.Page, here: str) -> str:
    title = str(page.front["title"]).strip()
    sub_stage = page.front.get("sub_stage")
    if isinstance(sub_stage, str) and sub_stage.strip():
        title = f"{sub_stage.strip()} {title}"
    target = urllib.parse.quote(posixpath.relpath(page.rel, here), safe="/")
    return _link(title, target)


def _item_page(item: Item, used: Sequence[sitelib.Page], config: Config) -> bytes:
    kind, here = item.kind, posixpath.dirname(item.out)
    label = sitelib.STAGES[item.code][0]
    title = f"{item.id} {item.title}"
    rows = list(item.rows)
    if used:
        rows.append(("Used in", ", ".join(_page_link(page, here) for page in used)))
    url = f"{config[0].rstrip('/')}/blob/{config[1]}/{item.source}"
    rows.append(("Source", _link(item.source, url)))
    fence = _fence(item.body)
    content = [item.body] if item.body else []
    body = [_heading(title), "", *_table(("Field", "Value"), rows), ""]
    if kind is PROMPTS:
        body += ["## Prompt", "", f"{fence}text", *content, fence]
        if item.notes:
            body += ["", "## Notes", item.notes]
    else:
        body += ["## Source code", "", f"{fence}{item.lang}", *content, fence]
    front: list[tuple[str, str | int | bool]] = [
        ("title", title),
        ("parent", f"{label} {kind.plural}"),
        ("grand_parent", kind.library),
        ("nav_order", item.number),
        ("generated", True),
    ]
    return _page(front, item.source, body)


def _listing(kind: _Kind, items: Sequence[Item], here: str) -> list[str]:
    if not items:
        return [f"No {kind.plural} have been published yet."]
    rows = [
        (
            _link(item.id, posixpath.relpath(item.out, here)),
            _cell(item.title),
            _cell(item.purpose),
        )
        for item in items
    ]
    return _table(("ID", "Title", "Purpose"), rows)


def _library_page(kind: _Kind, items: Sequence[Item]) -> bytes:
    body = [_heading(kind.library), "", kind.intro[0], "", kind.intro[1], ""]
    body += _listing(kind, items, f"docs/{kind.plural}")
    front: list[tuple[str, str | int | bool]] = [
        ("title", kind.library),
        ("nav_order", kind.nav_order),
        ("has_children", True),
        ("generated", True),
    ]
    return _page(front, f"{kind.plural}/", body)


def _stage_page(kind: _Kind, code: str, items: Sequence[Item]) -> bytes:
    label, name = sitelib.STAGES[code]
    title = f"{label} {kind.plural}"
    body = [_heading(title), "", f"{kind.plural.capitalize()} for {name}.", ""]
    body += _listing(kind, items, f"docs/{kind.plural}/{code.lower()}")
    front: list[tuple[str, str | int | bool]] = [
        ("title", title),
        ("parent", kind.library),
        ("nav_order", list(sitelib.STAGES).index(code) + 1),
        ("has_children", True),
        ("generated", True),
    ]
    return _page(front, f"{kind.plural}/", body)


def _kind_pages(
    kind: _Kind,
    items: Sequence[Item],
    pages: Sequence[sitelib.Page],
    config: Config,
) -> dict[str, bytes]:
    ordered = sorted(items, key=lambda item: sitelib.id_sort_key(item.id))
    refs = _references(pages, kind.plural)
    out = {
        item.out: _item_page(item, refs.get(item.id, []), config) for item in ordered
    }
    out[f"docs/{kind.plural}/index.md"] = _library_page(kind, ordered)
    for code in sitelib.STAGES:
        mine = [item for item in ordered if item.code == code]
        if mine:
            out[f"docs/{kind.plural}/{code.lower()}/index.md"] = _stage_page(
                kind, code, mine
            )
    return out


def compute_outputs(root: Path) -> dict[str, bytes]:
    """Return every generated file as {POSIX path relative to root: bytes}."""
    root = Path(root)
    errors: list[str] = []
    images = _collect_images(root, errors)
    config = _read_config(root, errors)
    prompts = _unique(_collect_prompts(root, errors), errors)
    scripts = _unique(_collect_scripts(root, errors), errors)
    pages = _doc_pages(root, errors)
    if errors or config is None:
        raise InputError(errors)
    outputs = dict(images)
    for kind, items in ((PROMPTS, prompts), (SCRIPTS, scripts)):
        outputs.update(_kind_pages(kind, items, pages, config))
    return dict(sorted(outputs.items()))


# ---- plan and apply --------------------------------------------------------------
@dataclass
class Plan:
    """What a run would do (or did): paths relative to the root, sorted."""

    create: list[str] = field(default_factory=list)
    update: list[str] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)
    delete: list[str] = field(default_factory=list)
    stale: list[tuple[str, str]] = field(default_factory=list)  # (path, note)

    @property
    def drift(self) -> bool:
        """True when the tree differs from the outputs in any way."""
        return bool(self.create or self.update or self.delete or self.stale)


def _state(path: Path, data: bytes) -> str:
    if path.is_symlink():
        return "update"
    if not path.exists():
        return "create"
    try:
        return "unchanged" if path.read_bytes() == data else "update"
    except OSError:
        return "update"


def _is_generated(path: Path) -> bool:
    try:
        text = sitelib.read_text(path)
    except (OSError, UnicodeDecodeError):
        return False
    front = sitelib.parse_front_matter_full(text)
    return (
        not front.errors
        and front.front.get("generated") is True
        and f"<!-- {GENERATED_MARK}" in text
    )


def _keep_note(root: Path, rel: str) -> str:
    """Empty when --prune may delete the stale file, else why it is kept."""
    suffix = posixpath.splitext(rel)[1].lower()
    if rel.startswith("docs/assets/images/") and suffix in IMAGE_SUFFIXES:
        return ""
    if suffix == ".md":
        if _is_generated(root / rel):
            return ""
        return "not a generated page; never deleted"
    return "not an image or a generated page; never deleted"


def _owned_files(root: Path) -> set[str]:
    found: set[str] = set()
    for owned in OWNED_DIRS:
        found.update(_rel(root, path) for path in sitelib.walk_files(root, owned))
    return found


def build_plan(root: Path, outputs: dict[str, bytes], prune: bool) -> Plan:
    """Compare the tree with the outputs. Reads only; writes nothing."""
    plan = Plan()
    for rel, data in outputs.items():
        getattr(plan, _state(root / rel, data)).append(rel)
    for rel in sorted(_owned_files(root) - outputs.keys()):
        note = _keep_note(root, rel)
        if prune and not note:
            plan.delete.append(rel)
        else:
            plan.stale.append((rel, note))
    return plan


def _remove_empty_dirs(root: Path, rel: str) -> None:
    """Remove folders emptied by deleting rel, never leaving its owned folder."""
    owned = next(d for d in OWNED_DIRS if rel.startswith(d + "/"))
    top, folder = root / owned, (root / rel).parent
    while folder != top:
        try:
            folder.rmdir()
        except OSError:
            break
        folder = folder.parent


def apply_plan(root: Path, outputs: dict[str, bytes], plan: Plan) -> None:
    """Write created and updated files, then delete what the plan deletes."""
    for rel in (*plan.create, *plan.update):
        dest = root / rel
        try:
            dest.parent.mkdir(parents=True, exist_ok=True)
            if dest.is_symlink():
                dest.unlink()
            dest.write_bytes(outputs[rel])
        except OSError as exc:
            raise InputError(
                [f"{rel}: cannot write ({exc.strerror or type(exc).__name__})"]
            ) from exc
    for rel in plan.delete:
        try:
            (root / rel).unlink()
        except OSError as exc:
            raise InputError(
                [f"{rel}: cannot delete ({exc.strerror or type(exc).__name__})"]
            ) from exc
        _remove_empty_dirs(root, rel)


def _report(plan: Plan, mode: str) -> list[str]:
    """Plan lines, then one summary line. mode is plan, check or write."""
    lines = [f"create {rel}" for rel in plan.create]
    lines += [f"update {rel}" for rel in plan.update]
    lines += [f"delete {rel}" for rel in plan.delete]
    lines += [
        f"stale {rel} ({note})" if note else f"stale {rel}" for rel, note in plan.stale
    ]
    words = ("created", "updated", "deleted")
    if mode != "write":
        words = ("to create", "to update", "to delete")
    lines.append(
        f"sync: {mode}: {len(plan.create)} {words[0]}, {len(plan.update)} {words[1]}, "
        f"{len(plan.delete)} {words[2]}, {len(plan.stale)} stale, "
        f"{len(plan.unchanged)} unchanged"
    )
    return lines


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="sync.py",
        description="Generate docs/assets/images, docs/prompts and docs/scripts.",
    )
    parser.add_argument(
        "--root",
        default=str(Path(__file__).resolve().parents[2]),
        help="repository root (default: two levels above this file)",
    )
    parser.add_argument("--write", action="store_true", help="apply the plan")
    parser.add_argument(
        "--check", action="store_true", help="exit 1 on drift or stale files"
    )
    parser.add_argument(
        "--prune",
        action="store_true",
        help="with --write, delete stale images and stale generated pages",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Command line entry point; returns the exit code."""
    args = _parser().parse_args(argv)
    if args.check and (args.write or args.prune):
        print(
            "sync: --check cannot be combined with --write or --prune", file=sys.stderr
        )
        return 2
    root = Path(args.root).resolve()
    if not root.is_dir():
        print(f"sync: {args.root}: not a directory", file=sys.stderr)
        return 2
    try:
        outputs = compute_outputs(root)
        plan = build_plan(root, outputs, args.prune)
        if args.write:
            apply_plan(root, outputs, plan)
    except InputError as exc:
        for issue in exc.issues:
            print(f"sync: {issue}", file=sys.stderr)
        return 2
    mode = "write" if args.write else "check" if args.check else "plan"
    print("\n".join(_report(plan, mode)))
    return 1 if args.check and plan.drift else 0


if __name__ == "__main__":
    sys.exit(main())
