"""Tests for scripts/site/sync.py.

License: CC0-1.0. Every fixture repository is built in a temporary directory;
the real repository tree is never read or written. The command line runs in a
subprocess with --root and with the fixture as its working directory.

Run from the repository root:
    python3 -B -m unittest discover -s scripts/tests -p 'test_sync.py'
"""

import hashlib
import re
import subprocess  # nosec B404
import sys
import tempfile
import unittest
from pathlib import Path

sys.dont_write_bytecode = True
SITE_DIR = Path(__file__).resolve().parents[1] / "site"
SYNC = SITE_DIR / "sync.py"
sys.path.insert(0, str(SITE_DIR))

import sitelib  # noqa: E402  # pylint: disable=wrong-import-position
import sync  # noqa: E402  # pylint: disable=wrong-import-position

BLOB = "https://example.org/acme/fixture/blob/main/"
SRC_PROMPT = "prompts/s1/search-plan.md"
SRC_SCRIPT = "scripts/s1/search_plan.py"
CONFIG = (
    'title: "Fixture"\n'
    'source_repo_url: "https://example.org/acme/fixture"\n'
    'source_branch: "main"\n'
)
INDEX_PAGE = 'title: "Home"\nnav_order: 1\n'
STAGE_PAGE = (
    "---\n"
    'title: "Search planning and execution"\n'
    "nav_order: 1\n"
    'stage: "S1"\n'
    'sub_stage: "S1.4a"\n'
    "prompts: [P-S1-04]\n"
    "scripts: [X-S1-01]\n"
    "---\n"
    "\n"
    "# Search planning and execution\n"
    "\n"
    "Body text.\n"
)
PROMPT = (
    "---\n"
    'id: "P-S1-04"\n'
    'title: "Search plan for one objective"\n'
    'stage: "S1"\n'
    'sub_stage: "S1.4a"\n'
    'purpose: "Draft a search plan for one learning objective."\n'
    'placeholders: ["OBJECTIVE_ID", "SOURCE_LIST"]\n'
    'capabilities: ["file-read", "web-search"]\n'
    'inputs: "One objective and a list of sources."\n'
    "---\n"
    "````text\n"
    "Plan a search for objective {{OBJECTIVE_ID}}.\n"
    "Use only these sources: {{SOURCE_LIST}}.\n"
    "````\n"
    "\n"
    "Keep the plan short.\n"
)
SCRIPT_BODY = "\nimport sys\n\nprint(sys.argv[1:])\n"
SCRIPT = (
    '"""\n'
    "ID: X-S1-01\n"
    "Title: Search plan runner\n"
    "Stage: S1\n"
    "Purpose: Print a search plan for one objective.\n"
    "Usage: python3 scripts/s1/search_plan.py --objective TEXT\n"
    "Dependencies: stdlib\n"
    "Writes files: no\n"
    "License: CC0-1.0\n"
    "Inputs: One objective given on the command line.\n"
    "Outputs: The plan on standard output.\n"
    '"""\n' + SCRIPT_BODY
)
HELPER = (
    '"""\n'
    "ID: X-OP-01\n"
    "Stage: OP\n"
    "Purpose: Shared helper.\n"
    "Usage: import text_helper\n"
    "Dependencies: stdlib\n"
    "Writes files: no\n"
    "License: CC0-1.0\n"
    '"""\n'
)
SVG = b'<svg xmlns="http://www.w3.org/2000/svg">\r\n</svg>\r\n\xff\xfe\x00'
COMMENT = "<!-- GENERATED by scripts/site/sync.py from {}. Do not edit. -->"
STALE_PAGE = (
    "---\n"
    'title: "Gone"\n'
    "generated: true\n"
    "---\n" + COMMENT.format("prompts/s9/gone.md") + "\n"
    "{% raw %}\n"
    "\n"
    "# Gone\n"
    "{% endraw %}\n"
)
EXPECTED_KEYS = [
    "docs/assets/images/diagram.svg",
    "docs/prompts/index.md",
    "docs/prompts/s1/index.md",
    "docs/prompts/s1/p-s1-04.md",
    "docs/scripts/index.md",
    "docs/scripts/op/index.md",
    "docs/scripts/op/x-op-01.md",
    "docs/scripts/s1/index.md",
    "docs/scripts/s1/x-s1-01.md",
]


def put(base: Path, rel: str, text: str, eol: str = "\n") -> None:
    """Write UTF-8 text with the given line ending, creating folders."""
    path = base / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(text.replace("\n", eol).encode("utf-8"))


def build_fixture(base: Path, eol: str = "\n") -> None:
    """A minimal repository: one prompt, two scripts, one image, two READMEs."""
    put(base, "docs/_config.yml", CONFIG, eol)
    put(base, "docs/index.md", "---\n" + INDEX_PAGE + "---\n\n# Home\n", eol)
    put(base, "docs/stage-1/search.md", STAGE_PAGE, eol)
    put(base, "prompts/s1/search-plan.md", PROMPT, eol)
    put(base, "prompts/README.md", "# Prompts\n", eol)
    put(base, "scripts/s1/search_plan.py", SCRIPT, eol)
    put(base, "scripts/common/text_helper.py", HELPER, eol)
    put(base, "images/README.md", "# Images\n", eol)
    (base / "images").mkdir(exist_ok=True)
    (base / "images" / "diagram.svg").write_bytes(SVG)


def snapshot(base: Path) -> dict[str, str]:
    """Map every path under base to a SHA-256 (or 'dir')."""
    snap = {}
    for path in sorted(base.rglob("*")):
        rel = path.relative_to(base).as_posix()
        if path.is_dir():
            snap[rel] = "dir"
        else:
            snap[rel] = hashlib.sha256(path.read_bytes()).hexdigest()
    return snap


def run_cli(base: Path, *args: str) -> subprocess.CompletedProcess[str]:
    """Run sync.py with --root and the fixture as the working directory."""
    return subprocess.run(  # nosec B603
        [sys.executable, "-B", str(SYNC), "--root", str(base), *args],
        capture_output=True,
        text=True,
        check=False,
        cwd=base,
    )


def page(outputs: dict[str, bytes], rel: str) -> str:
    return outputs[rel].decode("utf-8")


def with_body(body: str) -> str:
    """The fixture prompt as P-S1-05 with a new body that uses one placeholder."""
    text = PROMPT.replace('"P-S1-04"', '"P-S1-05"').replace(', "SOURCE_LIST"', "")
    old = (
        "Plan a search for objective {{OBJECTIVE_ID}}.\n"
        "Use only these sources: {{SOURCE_LIST}}."
    )
    return text.replace(old, body)


class FixtureCase(unittest.TestCase):
    """Each test gets its own fixture repository in a temporary directory."""

    def setUp(self) -> None:
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.root = Path(tmp.name)
        build_fixture(self.root)

    def read(self, rel: str) -> str:
        return (self.root / rel).read_text(encoding="utf-8")

    def edit(self, rel: str, old: str, new: str) -> None:
        text = self.read(rel)
        self.assertIn(old, text)
        put(self.root, rel, text.replace(old, new, 1))

    def outputs(self) -> dict[str, bytes]:
        return sync.compute_outputs(self.root)

    def cli_ok(self, *args: str) -> subprocess.CompletedProcess[str]:
        proc = run_cli(self.root, *args)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        return proc

    def cli_exit2(self, *args: str) -> str:
        """Run the CLI, expect exit 2, no output and no traceback; return stderr."""
        before = snapshot(self.root)
        proc = run_cli(self.root, *args)
        self.assertEqual(proc.returncode, 2, proc.stdout)
        self.assertEqual(proc.stdout, "")
        self.assertNotIn("Traceback", proc.stderr)
        self.assertEqual(snapshot(self.root), before)
        return proc.stderr


class PageTests(FixtureCase):
    def test_owned_dirs(self) -> None:
        self.assertEqual(
            sync.OWNED_DIRS,
            ("docs/assets/images", "docs/prompts", "docs/scripts"),
        )

    def test_output_paths_are_sorted_posix(self) -> None:
        self.assertEqual(EXPECTED_KEYS, sorted(EXPECTED_KEYS))
        self.assertEqual(list(self.outputs()), EXPECTED_KEYS)

    def test_front_matter_on_line_one_then_generated_comment(self) -> None:
        outputs = self.outputs()
        for rel in EXPECTED_KEYS:
            if not rel.endswith(".md"):
                continue
            with self.subTest(rel=rel):
                lines = page(outputs, rel).split("\n")
                self.assertEqual(lines[0], "---")
                close = lines.index("---", 1)
                self.assertTrue(
                    lines[close + 1].startswith(
                        "<!-- GENERATED by scripts/site/sync.py from "
                    )
                )
                self.assertTrue(lines[close + 1].endswith(". Do not edit. -->"))
                self.assertEqual(lines[close + 2], "{% raw %}")
        lines = page(outputs, "docs/prompts/s1/p-s1-04.md").split("\n")
        self.assertEqual(lines[6], "---")
        self.assertEqual(lines[7], COMMENT.format("prompts/s1/search-plan.md"))

    def test_front_matter_navigation_fields(self) -> None:
        outputs = self.outputs()
        expected = {
            "docs/prompts/s1/p-s1-04.md": {
                "title": "P-S1-04 Search plan for one objective",
                "parent": "Stage 1 prompts",
                "grand_parent": "Prompt library",
                "nav_order": 4,
                "generated": True,
            },
            "docs/prompts/s1/index.md": {
                "title": "Stage 1 prompts",
                "parent": "Prompt library",
                "nav_order": 1,
                "has_children": True,
                "generated": True,
            },
            "docs/prompts/index.md": {
                "title": "Prompt library",
                "nav_order": 80,
                "has_children": True,
                "generated": True,
            },
            "docs/scripts/index.md": {
                "title": "Script library",
                "nav_order": 81,
                "has_children": True,
                "generated": True,
            },
            "docs/scripts/s1/x-s1-01.md": {
                "title": "X-S1-01 Search plan runner",
                "parent": "Stage 1 scripts",
                "grand_parent": "Script library",
                "nav_order": 1,
                "generated": True,
            },
            "docs/scripts/op/index.md": {
                "title": "Operating practice scripts",
                "parent": "Script library",
                "nav_order": 8,
                "has_children": True,
                "generated": True,
            },
            "docs/scripts/op/x-op-01.md": {
                "title": "X-OP-01 text helper",
                "parent": "Operating practice scripts",
                "grand_parent": "Script library",
                "nav_order": 1,
                "generated": True,
            },
        }
        for rel, front in expected.items():
            with self.subTest(rel=rel):
                parsed, _, _, errors = sitelib.parse_front_matter(page(outputs, rel))
                self.assertEqual(errors, [])
                self.assertEqual(parsed, front)
                self.assertEqual(list(parsed), list(front))

    def test_prompt_page_is_exactly_the_template(self) -> None:
        expected = "\n".join(
            [
                "---",
                'title: "P-S1-04 Search plan for one objective"',
                'parent: "Stage 1 prompts"',
                'grand_parent: "Prompt library"',
                "nav_order: 4",
                "generated: true",
                "---",
                COMMENT.format("prompts/s1/search-plan.md"),
                "{% raw %}",
                "",
                "# P-S1-04 Search plan for one objective",
                "",
                "| Field | Value |",
                "|---|---|",
                "| Purpose | Draft a search plan for one learning objective. |",
                "| Sub-stage | S1.4a |",
                "| Inputs | One objective and a list of sources. |",
                "| Needs | `file-read`, `web-search` |",
                "| Placeholders | `{{OBJECTIVE_ID}}`, `{{SOURCE_LIST}}` |",
                "| Used in | [S1.4a Search planning and execution]"
                "(../../stage-1/search.md) |",
                "| Source | [prompts/s1/search-plan.md](" + BLOB + SRC_PROMPT + ") |",
                "",
                "## Prompt",
                "",
                "````text",
                "Plan a search for objective {{OBJECTIVE_ID}}.",
                "Use only these sources: {{SOURCE_LIST}}.",
                "````",
                "",
                "## Notes",
                "Keep the plan short.",
                "{% endraw %}",
                "",
            ]
        )
        self.assertEqual(page(self.outputs(), "docs/prompts/s1/p-s1-04.md"), expected)

    def test_script_page_is_exactly_the_template(self) -> None:
        expected = "\n".join(
            [
                "---",
                'title: "X-S1-01 Search plan runner"',
                'parent: "Stage 1 scripts"',
                'grand_parent: "Script library"',
                "nav_order: 1",
                "generated: true",
                "---",
                COMMENT.format("scripts/s1/search_plan.py"),
                "{% raw %}",
                "",
                "# X-S1-01 Search plan runner",
                "",
                "| Field | Value |",
                "|---|---|",
                "| Purpose | Print a search plan for one objective. |",
                "| Usage | python3 scripts/s1/search\\_plan.py --objective TEXT |",
                "| Dependencies | stdlib |",
                "| Writes files | no |",
                "| License | CC0-1.0 |",
                "| Inputs | One objective given on the command line. |",
                "| Outputs | The plan on standard output. |",
                "| Used in | [S1.4a Search planning and execution]"
                "(../../stage-1/search.md) |",
                "| Source | [scripts/s1/search\\_plan.py](" + BLOB + SRC_SCRIPT + ") |",
                "",
                "## Source code",
                "",
                "````python",
                SCRIPT.removesuffix("\n"),
                "````",
                "{% endraw %}",
                "",
            ]
        )
        self.assertEqual(page(self.outputs(), "docs/scripts/s1/x-s1-01.md"), expected)

    def test_common_script_goes_under_op_and_has_no_used_in_row(self) -> None:
        text = page(self.outputs(), "docs/scripts/op/x-op-01.md")
        self.assertNotIn("| Used in |", text)
        self.assertIn("| Source | [scripts/common/text\\_helper.py](" + BLOB, text)
        self.assertIn("## Source code\n\n````python\n", text)

    def test_used_in_does_not_double_a_title_that_already_has_the_sub_stage(
        self,
    ) -> None:
        """A stage page's own convention titles it "<sub_stage> <name>"; the
        "Used in" link must not prefix that code a second time."""
        page_obj = sitelib.Page(
            path=Path("docs/stage-1/search.md"),
            rel="docs/stage-1/search.md",
            front={
                "title": "S1.4a Search planning and execution",
                "sub_stage": "S1.4a",
            },
            body="",
            body_line_offset=0,
        )
        link = sync._page_link(page_obj, "docs/prompts/s1")
        self.assertEqual(
            link, "[S1.4a Search planning and execution](../../stage-1/search.md)"
        )

    def test_used_in_adds_the_sub_stage_when_the_title_omits_it(self) -> None:
        page_obj = sitelib.Page(
            path=Path("docs/stage-1/search.md"),
            rel="docs/stage-1/search.md",
            front={"title": "Search planning and execution", "sub_stage": "S1.4a"},
            body="",
            body_line_offset=0,
        )
        link = sync._page_link(page_obj, "docs/prompts/s1")
        self.assertEqual(
            link, "[S1.4a Search planning and execution](../../stage-1/search.md)"
        )

    def test_raw_block_wraps_the_whole_body(self) -> None:
        outputs = self.outputs()
        for rel in EXPECTED_KEYS:
            if not rel.endswith(".md"):
                continue
            with self.subTest(rel=rel):
                text = page(outputs, rel)
                self.assertEqual(text.count("{% raw %}"), 1)
                self.assertEqual(text.count("{% endraw %}"), 1)
                start = text.index("{% raw %}")
                end = text.index("{% endraw %}")
                before, after = text[:start], text[end + len("{% endraw %}") :]
                self.assertNotIn("{{", before)
                self.assertNotIn("{%", before)
                self.assertEqual(after, "\n")
                self.assertGreater(text.index("\n# "), start)
                self.assertLess(text.rindex("\n#"), end)
        text = page(outputs, "docs/prompts/s1/p-s1-04.md")
        start, end = text.index("{% raw %}"), text.index("{% endraw %}")
        self.assertLess(start, text.index("{{OBJECTIVE_ID}}"))
        self.assertGreater(end, text.rindex("{{SOURCE_LIST}}"))

    def test_triple_backtick_block_in_prompt_is_fenced_correctly(self) -> None:
        body = (
            "Return this JSON:\n"
            "```json\n"
            '{"objective": "{{OBJECTIVE_ID}}"}\n'
            "```\n"
            "Nothing else."
        )
        put(
            self.root,
            "prompts/s1/json-plan.md",
            with_body(body),
        )
        text = page(self.outputs(), "docs/prompts/s1/p-s1-05.md")
        self.assertIn("\n## Prompt\n\n````text\n" + body + "\n````\n", text)
        fences = [f for f in sitelib.find_fences(text) if f.marker == "````"]
        self.assertEqual(len(fences), 1)
        self.assertEqual(fences[0].lang, "text")
        self.assertEqual(fences[0].content, body)

    def test_longer_backtick_run_grows_the_prompt_fence(self) -> None:
        body = "Wrap it in `````like this````` please {{OBJECTIVE_ID}}."
        put(
            self.root,
            "prompts/s1/long-run.md",
            with_body(body),
        )
        text = page(self.outputs(), "docs/prompts/s1/p-s1-05.md")
        self.assertIn("\n``````text\n" + body + "\n``````\n", text)

    def test_longer_backtick_run_grows_the_script_fence(self) -> None:
        source = SCRIPT.replace("import sys\n", 'TICKS = "````"\n')
        put(self.root, "scripts/s1/search_plan.py", source)
        text = page(self.outputs(), "docs/scripts/s1/x-s1-01.md")
        self.assertIn("\n`````python\n" + source.removesuffix("\n") + "\n`````\n", text)

    def test_shell_script_uses_bash_fence(self) -> None:
        shell = (
            "#!/bin/sh\n"
            "# ID: X-S1-02\n"
            "# Purpose: Say hello.\n"
            "# Usage: sh scripts/s1/hello.sh\n"
            "# Dependencies: stdlib\n"
            "# Writes files: no\n"
            "# License: CC0-1.0\n"
            "\n"
            "echo hello\n"
        )
        put(self.root, "scripts/s1/hello.sh", shell)
        outputs = self.outputs()
        text = page(outputs, "docs/scripts/s1/x-s1-02.md")
        self.assertIn('title: "X-S1-02 hello"\n', text)
        self.assertIn("\n````bash\n" + shell.removesuffix("\n") + "\n````\n", text)

    def test_used_in_link_text_and_relative_path(self) -> None:
        put(
            self.root,
            "docs/other.md",
            '---\ntitle: "Other page"\nnav_order: 2\nscripts: [X-S1-01]\n---\n\n# O\n',
        )
        outputs = self.outputs()
        self.assertIn(
            "| Used in | [S1.4a Search planning and execution]"
            "(../../stage-1/search.md) |\n",
            page(outputs, "docs/prompts/s1/p-s1-04.md"),
        )
        self.assertIn(
            "| Used in | [Other page](../../other.md), "
            "[S1.4a Search planning and execution](../../stage-1/search.md) |\n",
            page(outputs, "docs/scripts/s1/x-s1-01.md"),
        )

    def test_used_in_ignores_generated_and_owned_pages(self) -> None:
        listing = '---\ntitle: "{}"\nnav_order: 3\nprompts: [P-S1-04]\n{}---\n\n# X\n'
        put(self.root, "docs/prompts/hand.md", listing.format("Hand", ""))
        put(self.root, "docs/mark.md", listing.format("Mark", "generated: true\n"))
        put(self.root, "docs/untitled.md", "---\nprompts: [P-S1-04]\n---\n\n# X\n")
        text = page(self.outputs(), "docs/prompts/s1/p-s1-04.md")
        self.assertEqual(text.count("| Used in |"), 1)
        self.assertNotIn("Hand", text)
        self.assertNotIn("Mark", text)

    def test_readmes_and_ignored_names_are_not_published(self) -> None:
        for rel, text in (
            ("prompts/s1/README.md", "# Nothing\n"),
            ("prompts/s1/_draft.md", "no front matter\n"),
            ("prompts/s1/.hidden.md", "no front matter\n"),
            ("prompts/s1/sub/deep.md", "no front matter\n"),
            ("prompts/s9/x.md", "no front matter\n"),
            ("prompts/notes.md", "no front matter\n"),
            ("scripts/README.md", "# Scripts\n"),
            ("scripts/s1/__init__.py", "x = 1\n"),
            ("scripts/s1/_private.py", "x = 1\n"),
            ("scripts/s1/test_search.py", "x = 1\n"),
            ("scripts/s1/notes.txt", "x\n"),
            ("scripts/common/__init__.py", "x = 1\n"),
            ("scripts/common/README.md", "# Common\n"),
            ("scripts/site/tool.py", "x = 1\n"),
            ("scripts/tests/test_tool.py", "x = 1\n"),
            ("scripts/sample_data/data.py", "x = 1\n"),
            ("images/.hidden.svg", "<svg/>\n"),
            ("images/.cache/inner.svg", "<svg/>\n"),
            ("images/notes.txt", "x\n"),
        ):
            put(self.root, rel, text)
        outputs = self.outputs()
        self.assertEqual(list(outputs), EXPECTED_KEYS)
        for rel in outputs:
            self.assertNotIn("readme", rel.lower())

    def test_stage_index_only_for_stages_with_items(self) -> None:
        outputs = self.outputs()
        for rel in (
            "docs/prompts/s1/index.md",
            "docs/scripts/s1/index.md",
            "docs/scripts/op/index.md",
        ):
            self.assertIn(rel, outputs)
        for code in ("s2", "s3", "s4", "s5", "ca", "dl", "op"):
            self.assertNotIn(f"docs/prompts/{code}/index.md", outputs)
        for code in ("s2", "s3", "s4", "s5", "ca", "dl"):
            self.assertNotIn(f"docs/scripts/{code}/index.md", outputs)

    def test_top_level_indexes_always_exist(self) -> None:
        (self.root / "prompts" / "s1" / "search-plan.md").unlink()
        outputs = self.outputs()
        self.assertNotIn("docs/prompts/s1/index.md", outputs)
        text = page(outputs, "docs/prompts/index.md")
        self.assertIn("No prompts have been published yet.\n", text)
        self.assertNotIn("| ID |", text)
        self.assertIn("docs/scripts/index.md", outputs)

    def test_index_tables_link_every_item_in_id_order(self) -> None:
        for rel, item_id, name in (
            ("prompts/s1/aaa.md", "P-S1-10", "Second search plan"),
            ("prompts/s2/bbb.md", "P-S2-01", "Draft outline"),
            ("prompts/op/ccc.md", "P-OP-02", "Log a decision"),
        ):
            code = item_id.split("-")[1]
            put(
                self.root,
                rel,
                PROMPT.replace('"P-S1-04"', f'"{item_id}"')
                .replace('stage: "S1"', f'stage: "{code}"')
                .replace("Search plan for one objective", name),
            )
        outputs = self.outputs()
        row = "| [{}]({}) | {} | Draft a search plan for one learning objective. |"
        library = page(outputs, "docs/prompts/index.md")
        self.assertIn(
            "\n".join(
                [
                    "| ID | Title | Purpose |",
                    "|---|---|---|",
                    row.format(
                        "P-S1-04", "s1/p-s1-04.md", "Search plan for one objective"
                    ),
                    row.format("P-S1-10", "s1/p-s1-10.md", "Second search plan"),
                    row.format("P-S2-01", "s2/p-s2-01.md", "Draft outline"),
                    row.format("P-OP-02", "op/p-op-02.md", "Log a decision"),
                ]
            )
            + "\n{% endraw %}\n",
            library,
        )
        stage = page(outputs, "docs/prompts/s1/index.md")
        self.assertIn(
            "\n".join(
                [
                    "# Stage 1 prompts",
                    "",
                    "Prompts for Knowledge acquisition.",
                    "",
                    "| ID | Title | Purpose |",
                    "|---|---|---|",
                    row.format(
                        "P-S1-04", "p-s1-04.md", "Search plan for one objective"
                    ),
                    row.format("P-S1-10", "p-s1-10.md", "Second search plan"),
                    "{% endraw %}",
                ]
            ),
            stage,
        )

    def test_table_cells_escape_pipes_and_collapse_newlines(self) -> None:
        source = SCRIPT.replace(
            "Usage: python3 scripts/s1/search_plan.py --objective TEXT\n",
            "Usage: python3 scripts/s1/search_plan.py a | b\n    second line\n",
        ).replace("Purpose: Print", "Purpose: Print | and")
        put(self.root, "scripts/s1/search_plan.py", source)
        outputs = self.outputs()
        text = page(outputs, "docs/scripts/s1/x-s1-01.md")
        self.assertIn(
            "| Usage | python3 scripts/s1/search\\_plan.py a \\| b second line |\n",
            text,
        )
        self.assertIn(
            "| Purpose | Print \\| and a search plan for one objective. |\n", text
        )
        index = page(outputs, "docs/scripts/s1/index.md")
        self.assertIn(
            "| [X-S1-01](x-s1-01.md) | Search plan runner | "
            "Print \\| and a search plan for one objective. |\n",
            index,
        )

    def test_front_matter_strings_are_quoted_and_escaped(self) -> None:
        title = 'Say "hi" \\ bye'
        put(
            self.root,
            "prompts/s1/quoted.md",
            PROMPT.replace('"P-S1-04"', '"P-S1-05"').replace(
                "Search plan for one objective", 'Say \\"hi\\" \\\\ bye'
            ),
        )
        text = page(self.outputs(), "docs/prompts/s1/p-s1-05.md")
        self.assertIn('title: "P-S1-05 Say \\"hi\\" \\\\ bye"\n', text)
        front, _, _, errors = sitelib.parse_front_matter(text)
        self.assertEqual(errors, [])
        self.assertEqual(front["title"], "P-S1-05 " + title)

    def test_images_are_copied_byte_for_byte(self) -> None:
        (self.root / "images" / "sub").mkdir()
        (self.root / "images" / "sub" / "photo-1.jpeg").write_bytes(b"\xff\xd8\r\n")
        outputs = self.outputs()
        self.assertEqual(outputs["docs/assets/images/diagram.svg"], SVG)
        self.assertEqual(
            outputs["docs/assets/images/sub/photo-1.jpeg"], b"\xff\xd8\r\n"
        )

    def test_crlf_input_gives_lf_output(self) -> None:
        with tempfile.TemporaryDirectory() as crlf_tmp:
            crlf_root = Path(crlf_tmp)
            build_fixture(crlf_root, eol="\r\n")
            self.assertIn(
                b"\r\n", (crlf_root / "prompts/s1/search-plan.md").read_bytes()
            )
            crlf = sync.compute_outputs(crlf_root)
        self.assertEqual(crlf, self.outputs())
        for rel, data in crlf.items():
            if rel.endswith(".md"):
                self.assertNotIn(b"\r", data)
                self.assertTrue(data.endswith(b"\n"))
                self.assertFalse(data.endswith(b"\n\n"))

    def test_identical_inputs_in_two_roots_give_identical_bytes(self) -> None:
        with tempfile.TemporaryDirectory() as other_tmp:
            other = Path(other_tmp)
            build_fixture(other)
            self.assertEqual(sync.compute_outputs(other), self.outputs())
            self.assertEqual(list(sync.compute_outputs(other)), EXPECTED_KEYS)
            self.cli_ok("--write")
            self.assertEqual(run_cli(other, "--write").returncode, 0)
            self.assertEqual(snapshot(other), snapshot(self.root))


def cell(text: str, label: str) -> str:
    """The value cell of the metadata table row that starts with `| label |`."""
    prefix = f"| {label} | "
    rows = [line for line in text.split("\n") if line.startswith(prefix)]
    if len(rows) != 1:
        raise AssertionError(f"expected one {label!r} row, found {len(rows)}")
    return rows[0][len(prefix) : -len(" |")]


class EscapeTests(FixtureCase):
    """Markdown-significant characters are escaped in cells and H1, nowhere else."""

    PAGE = "docs/scripts/s1/x-s1-01.md"

    def script_page(self, **fields: str) -> str:
        """Replace header lines of the fixture script and return its page."""
        lines = SCRIPT.split("\n")
        for label, value in fields.items():
            index = next(i for i, ln in enumerate(lines) if ln.startswith(label + ":"))
            lines[index] = f"{label}: {value}"
        put(self.root, SRC_SCRIPT, "\n".join(lines))
        return page(self.outputs(), self.PAGE)

    def test_md_escape_examples(self) -> None:
        cases = {
            "": "",
            "plain text": "plain text",
            "<dir>": "\\<dir\\>",
            "LLM_BASE_URL": "LLM\\_BASE\\_URL",
            "a*b": "a\\*b",
            "[x](y)": "\\[x\\](y)",
            "a | b": "a \\| b",
            "back\\slash": "back\\\\slash",
            "`code_span_with_<tag>`": "`code_span_with_<tag>`",
            "use LLM_URL or `keep_this` and A*B": (
                "use LLM\\_URL or `keep_this` and A\\*B"
            ),
            "``a`b_c`` and d_e": "``a`b_c`` and d\\_e",
            "one ` tick_here": "one ` tick\\_here",
        }
        for text, expected in cases.items():
            with self.subTest(text=text):
                self.assertEqual(sync.md_escape(text), expected)

    def test_md_escape_in_a_table_also_escapes_pipes_inside_code_spans(self) -> None:
        self.assertEqual(sync.md_escape("`a|b` | c", table=True), "`a\\|b` \\| c")
        self.assertEqual(sync.md_escape("`a|b` | c"), "`a|b` \\| c")

    def test_angle_brackets_are_escaped_in_cells(self) -> None:
        text = self.script_page(Usage="python3 x.py <dir> --out <file>")
        self.assertEqual(cell(text, "Usage"), "python3 x.py \\<dir\\> --out \\<file\\>")

    def test_underscores_are_escaped_in_cells(self) -> None:
        text = self.script_page(Inputs="LLM_BASE_URL and LLM_API_KEY")
        self.assertEqual(cell(text, "Inputs"), "LLM\\_BASE\\_URL and LLM\\_API\\_KEY")

    def test_stars_and_link_syntax_are_escaped_in_cells(self) -> None:
        text = self.script_page(Outputs="a*b and [x](y)")
        self.assertEqual(cell(text, "Outputs"), "a\\*b and \\[x\\](y)")

    def test_code_span_is_untouched_in_a_cell(self) -> None:
        text = self.script_page(Usage="run `code_span_with_<tag>` now")
        self.assertEqual(cell(text, "Usage"), "run `code_span_with_<tag>` now")

    def test_mixed_plain_text_and_code_span_escapes_only_the_plain_part(self) -> None:
        text = self.script_page(Usage="set LLM_URL, keep `LLM_URL`, use a*b")
        self.assertEqual(
            cell(text, "Usage"), "set LLM\\_URL, keep `LLM_URL`, use a\\*b"
        )

    def test_value_with_a_pipe_stays_in_one_cell(self) -> None:
        for value, shown in (
            ("Read a | b", "Read a \\| b"),
            ("Run `x a|b` now", "Run `x a\\|b` now"),
        ):
            with self.subTest(value=value):
                text = self.script_page(Purpose=value)
                self.assertEqual(cell(text, "Purpose"), shown)
                row = next(ln for ln in text.split("\n") if ln.startswith("| Purpose"))
                self.assertEqual(len(re.split(r"(?<!\\)\|", row)), 4)

    def test_h1_is_escaped_but_front_matter_is_not(self) -> None:
        text = self.script_page(Title="Fast_run [beta] <x> a*b")
        self.assertIn("\n# X-S1-01 Fast\\_run \\[beta\\] \\<x\\> a\\*b\n", text)
        self.assertIn('\ntitle: "X-S1-01 Fast_run [beta] <x> a*b"\n', text)

    def test_index_table_cells_are_escaped(self) -> None:
        self.script_page(Title="Fast_run [beta]", Purpose="Use <dir> | LLM_URL")
        index = page(self.outputs(), "docs/scripts/s1/index.md")
        library = page(self.outputs(), "docs/scripts/index.md")
        row = "| [X-S1-01]({}x-s1-01.md) | Fast\\_run \\[beta\\] | "
        row += "Use \\<dir\\> \\| LLM\\_URL |\n"
        self.assertIn(row.format(""), index)
        self.assertIn(row.format("s1/"), library)

    def test_used_in_link_text_is_escaped(self) -> None:
        self.edit("docs/stage-1/search.md", '"Search planning', '"Search_plan <x>')
        text = page(self.outputs(), "docs/prompts/s1/p-s1-04.md")
        self.assertEqual(
            cell(text, "Used in"),
            "[S1.4a Search\\_plan \\<x\\> and execution](../../stage-1/search.md)",
        )

    def test_prompt_page_escapes_h1_and_cells_but_not_the_fence(self) -> None:
        body = "Use <dir> and LLM_BASE_URL, a*b, [x](y), a | b \\ {{OBJECTIVE_ID}}."
        source = (
            with_body(body)
            .replace("Search plan for one objective", "Plan_x [beta]")
            .replace("Draft a search plan", "Use <dir> | LLM_URL")
        )
        put(self.root, "prompts/s1/special.md", source)
        text = page(self.outputs(), "docs/prompts/s1/p-s1-05.md")
        self.assertIn("\n# P-S1-05 Plan\\_x \\[beta\\]\n", text)
        self.assertIn('\ntitle: "P-S1-05 Plan_x [beta]"\n', text)
        self.assertEqual(
            cell(text, "Purpose"),
            "Use \\<dir\\> \\| LLM\\_URL for one learning objective.",
        )
        fences = [f for f in sitelib.find_fences(text) if f.marker == "````"]
        self.assertEqual([f.content for f in fences], [body])

    def test_fenced_source_is_byte_identical(self) -> None:
        source = SCRIPT.replace(
            "import sys\n",
            'X = "<dir> LLM_BASE_URL a*b [x](y) a | b \\\\ `c_d`"\n',
        )
        put(self.root, SRC_SCRIPT, source)
        text = page(self.outputs(), self.PAGE)
        self.assertIn("\n````python\n" + source.removesuffix("\n") + "\n````\n", text)
        fences = [f for f in sitelib.find_fences(text) if f.marker == "````"]
        self.assertEqual([f.content for f in fences], [source.removesuffix("\n")])


class InputErrorTests(FixtureCase):
    def test_endraw_in_prompt_exits_2(self) -> None:
        self.edit("prompts/s1/search-plan.md", "short.\n", "short.\n{% endraw %}\n")
        line = self.read("prompts/s1/search-plan.md").split("\n").index("{% endraw %}")
        self.assertEqual(
            self.cli_exit2(),
            f"sync: prompts/s1/search-plan.md: line {line + 1}: "
            "'{% endraw' would end the generated raw block\n",
        )

    def test_endraw_in_script_exits_2(self) -> None:
        self.edit("scripts/s1/search_plan.py", "print(", "# {%endraw%}\nprint(")
        lines = self.read("scripts/s1/search_plan.py").split("\n")
        self.assertEqual(lines.index("# {%endraw%}"), 15)
        self.assertEqual(
            self.cli_exit2("--write"),
            "sync: scripts/s1/search_plan.py: line 16: "
            "'{% endraw' would end the generated raw block\n",
        )

    def test_missing_config_key_exits_2(self) -> None:
        self.edit("docs/_config.yml", 'source_branch: "main"\n', "")
        self.assertEqual(
            self.cli_exit2(),
            "sync: docs/_config.yml: missing or empty key 'source_branch'\n",
        )

    def test_missing_config_url_exits_2(self) -> None:
        self.edit("docs/_config.yml", "source_repo_url:", "other_key:")
        self.assertEqual(
            self.cli_exit2("--write"),
            "sync: docs/_config.yml: missing or empty key 'source_repo_url'\n",
        )

    def test_missing_config_file_exits_2(self) -> None:
        (self.root / "docs" / "_config.yml").unlink()
        self.assertTrue(
            self.cli_exit2().startswith("sync: docs/_config.yml: cannot read (")
        )

    def test_duplicate_ids_exit_2(self) -> None:
        put(self.root, "prompts/s1/copy.md", PROMPT)
        self.assertEqual(
            self.cli_exit2(),
            "sync: prompts/s1/search-plan.md: duplicate ID P-S1-04 "
            "(also in prompts/s1/copy.md)\n",
        )

    def test_duplicate_script_ids_across_op_and_common_exit_2(self) -> None:
        put(self.root, "scripts/op/twin.py", HELPER)
        self.assertEqual(
            self.cli_exit2(),
            "sync: scripts/common/text_helper.py: duplicate ID X-OP-01 "
            "(also in scripts/op/twin.py)\n",
        )

    def test_script_stage_disagreeing_with_folder_exits_2(self) -> None:
        self.edit("scripts/s1/search_plan.py", "Stage: S1", "Stage: S2")
        self.assertEqual(
            self.cli_exit2(),
            "sync: scripts/s1/search_plan.py: line 4: Stage 'S2' disagrees with "
            "the ID code and scripts/s1\n",
        )

    def test_script_id_code_disagreeing_with_folder_exits_2(self) -> None:
        self.edit("scripts/s1/search_plan.py", "ID: X-S1-01", "ID: X-S2-01")
        self.assertEqual(
            self.cli_exit2(),
            "sync: scripts/s1/search_plan.py: line 2: ID X-S2-01 has stage code "
            "S2, but scripts/s1 is for S1\n",
        )

    def test_common_script_with_other_stage_code_exits_2(self) -> None:
        self.edit("scripts/common/text_helper.py", "X-OP-01", "X-S1-09")
        self.assertIn(
            "ID X-S1-09 has stage code S1, but scripts/common is for OP",
            self.cli_exit2(),
        )

    def test_prompt_id_code_disagreeing_with_folder_exits_2(self) -> None:
        self.edit("prompts/s1/search-plan.md", '"P-S1-04"', '"P-S2-04"')
        self.assertEqual(
            self.cli_exit2(),
            "sync: prompts/s1/search-plan.md: line 2: ID P-S2-04 has stage code "
            "S2, but prompts/s1 is for S1\n",
        )

    def test_prompt_stage_disagreeing_with_folder_exits_2(self) -> None:
        self.edit("prompts/s1/search-plan.md", 'stage: "S1"', 'stage: "S2"')
        self.assertEqual(
            self.cli_exit2(),
            "sync: prompts/s1/search-plan.md: line 4: stage 'S2' disagrees with "
            "the ID code and prompts/s1\n",
        )

    def test_malformed_id_exits_2(self) -> None:
        self.edit("prompts/s1/search-plan.md", '"P-S1-04"', '"P-S1-4"')
        stderr = self.cli_exit2()
        self.assertTrue(
            stderr.startswith(
                "sync: prompts/s1/search-plan.md: line 2: ID 'P-S1-4' must look like"
            )
        )

    def test_invalid_prompt_and_header_report_every_problem_and_exit_2(self) -> None:
        self.edit("prompts/s1/search-plan.md", "purpose:", "goal:")
        self.edit("scripts/s1/search_plan.py", "License: CC0-1.0", "License: MIT")
        stderr = self.cli_exit2()
        self.assertIn(
            "sync: prompts/s1/search-plan.md: line 1: missing required", stderr
        )
        self.assertIn(
            "sync: scripts/s1/search_plan.py: line 9: 'License' must be", stderr
        )

    def test_bad_image_name_exits_2(self) -> None:
        (self.root / "images" / "Bad Name.svg").write_bytes(b"<svg/>")
        self.assertEqual(
            self.cli_exit2(),
            "sync: images/Bad Name.svg: image names may use only a-z, 0-9, "
            "'.', '_', '-' and '/'\n",
        )

    def test_bad_image_folder_name_exits_2(self) -> None:
        (self.root / "images" / "Sub").mkdir()
        (self.root / "images" / "Sub" / "a.png").write_bytes(b"x")
        self.assertIn("sync: images/Sub/a.png: image names", self.cli_exit2())

    def test_unusual_source_file_name_exits_2(self) -> None:
        put(self.root, "prompts/s1/two words.md", PROMPT)
        self.assertEqual(
            self.cli_exit2(),
            "sync: prompts/s1/two words.md: file names may use only letters, "
            "digits, '.', '_' and '-'\n",
        )

    def test_title_with_liquid_syntax_exits_2(self) -> None:
        self.edit("scripts/s1/search_plan.py", "Search plan runner", "Run {{ x }}")
        self.assertIn("title must not contain", self.cli_exit2())

    def test_invalid_utf8_source_exits_2(self) -> None:
        (self.root / "prompts" / "s1" / "search-plan.md").write_bytes(b"\xff\xfe")
        self.assertEqual(
            self.cli_exit2(), "sync: prompts/s1/search-plan.md: not valid UTF-8\n"
        )

    def test_unreadable_docs_page_exits_2(self) -> None:
        (self.root / "docs" / "broken.md").write_bytes(b"---\n\xff\n---\n")
        self.assertEqual(self.cli_exit2(), "sync: docs/broken.md: not valid UTF-8\n")

    def test_compute_outputs_raises_input_error_with_issues(self) -> None:
        self.edit("docs/_config.yml", 'source_branch: "main"\n', "")
        with self.assertRaises(sync.InputError) as ctx:
            self.outputs()
        self.assertEqual(
            ctx.exception.issues,
            ["docs/_config.yml: missing or empty key 'source_branch'"],
        )


class CliTests(FixtureCase):
    def test_dry_run_prints_plan_and_leaves_tree_unchanged(self) -> None:
        before = snapshot(self.root)
        proc = self.cli_ok()
        self.assertEqual(snapshot(self.root), before)
        self.assertEqual(proc.stderr, "")
        self.assertEqual(
            proc.stdout,
            "".join(f"create {rel}\n" for rel in EXPECTED_KEYS)
            + "sync: plan: 9 to create, 0 to update, 0 to delete, 0 stale, "
            "0 unchanged\n",
        )

    def test_dry_run_with_stale_and_drift_leaves_tree_unchanged(self) -> None:
        self.cli_ok("--write")
        put(self.root, "docs/prompts/s1/old.md", "x\n")
        self.edit("docs/prompts/s1/p-s1-04.md", "Keep the plan", "Keep a plan")
        before = snapshot(self.root)
        proc = self.cli_ok()
        self.assertEqual(snapshot(self.root), before)
        self.assertEqual(
            proc.stdout,
            "update docs/prompts/s1/p-s1-04.md\n"
            "stale docs/prompts/s1/old.md (not a generated page; never deleted)\n"
            "sync: plan: 0 to create, 1 to update, 0 to delete, 1 stale, "
            "8 unchanged\n",
        )

    def test_write_creates_exactly_the_outputs_and_leaves_sources_alone(self) -> None:
        before = snapshot(self.root)
        proc = self.cli_ok("--write")
        self.assertEqual(
            proc.stdout,
            "".join(f"create {rel}\n" for rel in EXPECTED_KEYS)
            + "sync: write: 9 created, 0 updated, 0 deleted, 0 stale, 0 unchanged\n",
        )
        for rel, data in self.outputs().items():
            self.assertEqual((self.root / rel).read_bytes(), data)
        after = snapshot(self.root)
        for rel, digest in before.items():
            self.assertEqual(after[rel], digest, rel)
        created = {rel for rel in set(after) - set(before) if after[rel] != "dir"}
        self.assertEqual(created, set(EXPECTED_KEYS))

    def test_write_twice_is_a_no_op(self) -> None:
        self.cli_ok("--write")
        first = snapshot(self.root)
        stamps = {rel: (self.root / rel).stat().st_mtime_ns for rel in EXPECTED_KEYS}
        proc = self.cli_ok("--write")
        self.assertEqual(snapshot(self.root), first)
        self.assertEqual(
            {rel: (self.root / rel).stat().st_mtime_ns for rel in EXPECTED_KEYS},
            stamps,
        )
        self.assertEqual(
            proc.stdout,
            "sync: write: 0 created, 0 updated, 0 deleted, 0 stale, 9 unchanged\n",
        )

    def test_check_on_clean_tree_exits_0(self) -> None:
        self.cli_ok("--write")
        proc = self.cli_ok("--check")
        self.assertEqual(
            proc.stdout,
            "sync: check: 0 to create, 0 to update, 0 to delete, 0 stale, "
            "9 unchanged\n",
        )

    def test_check_before_any_write_exits_1(self) -> None:
        self.assertEqual(run_cli(self.root, "--check").returncode, 1)

    def check_fails(self, expected_line: str) -> None:
        before = snapshot(self.root)
        proc = run_cli(self.root, "--check")
        self.assertEqual(proc.returncode, 1, proc.stdout + proc.stderr)
        self.assertIn(expected_line + "\n", proc.stdout)
        self.assertEqual(snapshot(self.root), before)

    def test_check_fails_after_editing_a_source(self) -> None:
        self.cli_ok("--write")
        self.edit("prompts/s1/search-plan.md", "learning objective", "learning aim")
        self.check_fails("update docs/prompts/s1/p-s1-04.md")

    def test_check_fails_after_editing_a_copy(self) -> None:
        self.cli_ok("--write")
        with (self.root / "docs/prompts/s1/p-s1-04.md").open("a") as handle:
            handle.write("hand edit\n")
        self.check_fails("update docs/prompts/s1/p-s1-04.md")

    def test_check_fails_after_deleting_a_copy(self) -> None:
        self.cli_ok("--write")
        (self.root / "docs/assets/images/diagram.svg").unlink()
        self.check_fails("create docs/assets/images/diagram.svg")

    def test_check_fails_after_adding_a_stale_file(self) -> None:
        self.cli_ok("--write")
        put(self.root, "docs/scripts/s1/leftover.md", "x\n")
        self.check_fails(
            "stale docs/scripts/s1/leftover.md (not a generated page; never deleted)"
        )

    def test_check_fails_after_changing_an_image_source(self) -> None:
        self.cli_ok("--write")
        (self.root / "images" / "diagram.svg").write_bytes(SVG + b"x")
        self.check_fails("update docs/assets/images/diagram.svg")

    def test_check_fails_when_a_page_listing_changes_used_in(self) -> None:
        self.cli_ok("--write")
        self.edit("docs/stage-1/search.md", 'title: "Search', 'title: "Find')
        self.check_fails("update docs/prompts/s1/p-s1-04.md")

    def populate_stale_files(self) -> None:
        self.cli_ok("--write")
        (self.root / "docs/assets/images/old").mkdir()
        (self.root / "docs/assets/images/old/gone.png").write_bytes(b"png")
        put(self.root, "docs/prompts/s9/gone.md", STALE_PAGE)
        put(self.root, "docs/prompts/notes.md", "# Headerless notes\n")
        put(self.root, "docs/prompts/s1/marked.md", "---\ngenerated: true\n---\nx\n")
        put(
            self.root,
            "docs/prompts/s1/commented.md",
            '---\ntitle: "C"\n---\n' + COMMENT.format("nowhere") + "\n",
        )
        put(self.root, "docs/scripts/s1/leftover.txt", "x\n")
        (self.root / "docs" / "other" / "empty").mkdir(parents=True)

    def test_prune_deletes_stale_images_and_generated_pages_only(self) -> None:
        self.populate_stale_files()
        proc = self.cli_ok("--write", "--prune")
        lines = proc.stdout.splitlines()
        self.assertEqual(
            lines,
            [
                "delete docs/assets/images/old/gone.png",
                "delete docs/prompts/s9/gone.md",
                "stale docs/prompts/notes.md (not a generated page; never deleted)",
                "stale docs/prompts/s1/commented.md "
                "(not a generated page; never deleted)",
                "stale docs/prompts/s1/marked.md (not a generated page; never deleted)",
                "stale docs/scripts/s1/leftover.txt "
                "(not an image or a generated page; never deleted)",
                "sync: write: 0 created, 0 updated, 2 deleted, 4 stale, 9 unchanged",
            ],
        )
        root = self.root
        self.assertFalse((root / "docs/assets/images/old").exists())
        self.assertFalse((root / "docs/prompts/s9").exists())
        for kept in (
            "docs/prompts/notes.md",
            "docs/prompts/s1/marked.md",
            "docs/prompts/s1/commented.md",
            "docs/scripts/s1/leftover.txt",
            "docs/assets/images/diagram.svg",
        ):
            self.assertTrue((root / kept).is_file(), kept)
        self.assertTrue((root / "docs/other/empty").is_dir())
        self.assertEqual(run_cli(root, "--check").returncode, 1)

    def test_prune_without_write_deletes_nothing(self) -> None:
        self.populate_stale_files()
        before = snapshot(self.root)
        proc = self.cli_ok("--prune")
        self.assertEqual(snapshot(self.root), before)
        self.assertIn("delete docs/assets/images/old/gone.png\n", proc.stdout)
        self.assertIn("delete docs/prompts/s9/gone.md\n", proc.stdout)
        self.assertIn(
            "sync: plan: 0 to create, 0 to update, 2 to delete, 4 stale, 9 unchanged\n",
            proc.stdout,
        )

    def test_write_without_prune_reports_stale_and_deletes_nothing(self) -> None:
        self.populate_stale_files()
        before = snapshot(self.root)
        proc = self.cli_ok("--write")
        self.assertEqual(snapshot(self.root), before)
        self.assertIn("stale docs/assets/images/old/gone.png\n", proc.stdout)
        self.assertIn("stale docs/prompts/s9/gone.md\n", proc.stdout)

    def test_prune_never_removes_the_owned_folder_itself(self) -> None:
        self.cli_ok("--write")
        (self.root / "images" / "diagram.svg").unlink()
        proc = self.cli_ok("--write", "--prune")
        self.assertIn("delete docs/assets/images/diagram.svg\n", proc.stdout)
        self.assertTrue((self.root / "docs/assets/images").is_dir())
        self.assertEqual(list((self.root / "docs/assets/images").iterdir()), [])
        self.assertEqual(run_cli(self.root, "--check").returncode, 0)

    def test_prune_removes_pages_of_a_deleted_source(self) -> None:
        self.cli_ok("--write")
        (self.root / "prompts" / "s1" / "search-plan.md").unlink()
        proc = self.cli_ok("--write", "--prune")
        for rel in ("docs/prompts/s1/index.md", "docs/prompts/s1/p-s1-04.md"):
            self.assertIn(f"delete {rel}\n", proc.stdout)
        self.assertFalse((self.root / "docs/prompts/s1").exists())
        self.assertTrue((self.root / "docs/prompts/index.md").is_file())
        self.assertEqual(run_cli(self.root, "--check").returncode, 0)

    def test_check_with_write_or_prune_is_a_usage_error(self) -> None:
        message = "sync: --check cannot be combined with --write or --prune\n"
        for args in (
            ("--check", "--write"),
            ("--check", "--prune"),
            ("--check", "--write", "--prune"),
        ):
            with self.subTest(args=args):
                self.assertEqual(self.cli_exit2(*args), message)

    def test_unknown_option_exits_2_without_traceback(self) -> None:
        stderr = self.cli_exit2("--bogus")
        self.assertIn("unrecognized arguments: --bogus", stderr)

    def test_root_that_is_not_a_directory_exits_2(self) -> None:
        proc = subprocess.run(  # nosec B603
            [sys.executable, "-B", str(SYNC), "--root", str(self.root / "nope")],
            capture_output=True,
            text=True,
            check=False,
            cwd=self.root,
        )
        self.assertEqual(proc.returncode, 2)
        self.assertNotIn("Traceback", proc.stderr)
        self.assertTrue(proc.stderr.startswith("sync: "))

    def test_default_root_is_two_levels_above_the_script(self) -> None:
        site = self.root / "scripts" / "site"
        site.mkdir(parents=True)
        for name in ("sync.py", "sitelib.py"):
            (site / name).write_bytes((SITE_DIR / name).read_bytes())
        with tempfile.TemporaryDirectory() as elsewhere:
            proc = subprocess.run(  # nosec B603
                [sys.executable, "-B", str(site / "sync.py")],
                capture_output=True,
                text=True,
                check=False,
                cwd=elsewhere,
            )
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertEqual(
            proc.stdout,
            "".join(f"create {rel}\n" for rel in EXPECTED_KEYS)
            + "sync: plan: 9 to create, 0 to update, 0 to delete, 0 stale, "
            "0 unchanged\n",
        )
        self.assertEqual(
            sorted(p.name for p in site.iterdir()), ["sitelib.py", "sync.py"]
        )


if __name__ == "__main__":
    unittest.main()
