"""Tests for scripts/site/check.py.

License: CC0-1.0. Every fixture repository is built in a temporary directory
and passed with --root (or as the root argument); the real repository tree is
never read or written. The generated-file rule R11 runs against a fake ``sync``
module placed in sys.modules, so these tests never depend on the real
sync.py. Fake credentials, local paths and private terms are assembled at run
time, so this file holds no key-shaped or path-shaped literal.

Run from the repository root:
    python3 -B -m unittest discover -s scripts/tests -p 'test_check.py'
"""

import contextlib
import io
import os
import shutil
import subprocess  # nosec B404
import sys
import tempfile
import time
import types
import unittest
from collections.abc import Callable
from pathlib import Path
from typing import Any

sys.dont_write_bytecode = True
SITE_DIR = Path(__file__).resolve().parents[1] / "site"
sys.path.insert(0, str(SITE_DIR))

import check  # noqa: E402  # pylint: disable=wrong-import-position
import sitelib  # noqa: E402  # pylint: disable=wrong-import-position

FRONT = 'status: "draft"\nlast_reviewed: "2026-01-15"\n'
SVG = (
    '<svg xmlns="http://www.w3.org/2000/svg" width="40" height="20">'
    '<rect width="18" height="20"/><rect x="22" width="18" height="20"/></svg>\n'
)
PROMPTS_SECTION = (
    "## Prompts\n\n"
    "[P-S1-01 Example prompt](prompts/s1/p-s1-01.md) writes one sentence.\n\n"
)
SCRIPTS_SECTION = (
    "## Scripts\n\n"
    "[X-S1-01 Example script](scripts/s1/x-s1-01.md) prints a greeting.\n\n"
)
FENCE4 = "`" * 4
FENCE3 = "`" * 3

HOME = (
    '---\ntitle: "Home"\nnav_order: 1\n' + FRONT + "---\n\n"
    "# Fixture home\n\n"
    "This fixture site exists only to test the checker. It has one stage page,\n"
    "one prompt and one script, so every rule has something to look at.\n\n"
    "Read [the example sub-stage](s1-1-example.md) next. It shows the whole page\n"
    "template from the first section to the last, with one prompt and one script.\n\n"
    "Every page here is small on purpose. A checker test should fail for one\n"
    "reason only, so each page holds just enough text to stay clear of the\n"
    "style warnings, and nothing more than that.\n"
)

STAGE = (
    '---\ntitle: "S1.1 Example sub-stage"\nnav_order: 2\n' + FRONT + 'stage: "S1"\n'
    'sub_stage: "S1.1"\nprompts: ["P-S1-01"]\nscripts: ["X-S1-01"]\n---\n\n'
    "# S1.1 Example sub-stage\n\n"
    "## Outcome\n\n"
    "The reader ends with one printed greeting and a clear view of the page.\n\n"
    "## Where it fits\n\n"
    "This part follows the [home page](index.md) and hands nothing on.\n"
    "See [the steps](#steps) and [the home heading](index.md#fixture-home).\n\n"
    "## Why this way\n\n"
    "A short page with every section keeps the checker tests small.\n\n"
    "## Steps\n\n1. Read the prompt.\n2. Run the script.\n\n"
    "{% raw %}\n\n" + FENCE3 + "text\n# not a heading\n"
    "[not a link](no-such-file.md) and {{NAME}} and `inline {{X}}`\n"
    "<!-- [gone](nothing.md) {{Y}} -->\n" + FENCE3 + "\n\n{% endraw %}\n\n"
    "Inline code such as `[x](missing.md)` and `# no` is masked too.\n\n"
    "## Artifacts and formats\n\n"
    "The flow is drawn once. ![Flow diagram with two boxes](assets/images/flow.svg)\n\n"
    + PROMPTS_SECTION
    + SCRIPTS_SECTION
    + "## Definition of done\n\nThe greeting is on screen.\n\n"
    "## Common failures\n\nThe script is run from the wrong folder.\n\n"
    "## Adapting to your platform\n\nAny platform that runs Python works.\n\n"
    "## Where humans decide\n\nA person decides if the greeting is good enough.\n"
)

PROMPT = (
    '---\nid: "P-S1-01"\ntitle: "Example prompt"\nstage: "S1"\n'
    'sub_stage: "S1.1"\npurpose: "Show how a prompt file looks."\n'
    'placeholders: ["TOPIC"]\ncapabilities: ["llm"]\n---\n'
    + FENCE4
    + "text\nWrite one sentence about {{TOPIC}}.\n"
    + FENCE4
    + "\n\nNotes go here.\n"
)

SCRIPT = (
    '"""\nID: X-S1-01\nTitle: Example script\nStage: S1\n'
    "Purpose: Print a greeting.\nUsage: python3 scripts/s1/example.py\n"
    "Dependencies: stdlib\nWrites files: no\nLicense: CC0-1.0\n"
    '"""\n\nprint("hello")\n'
)

FOOTER = (
    "<p>Public domain.</p>\n"
    "<script src=\"{{ '/assets/js/x.js' | relative_url }}\" defer></script>\n"
)


def generated_page(
    title: str, nav: int, parent: str, grand: str, source: str, body: str
) -> str:
    """A page shaped like sync output (plan S7): raw block around the body."""
    lines = ["---", f'title: "{title}"']
    if parent:
        lines.append(f'parent: "{parent}"')
    if grand:
        lines.append(f'grand_parent: "{grand}"')
    lines += [f"nav_order: {nav}", "generated: true", "---"]
    lines += [f"<!-- GENERATED by scripts/site/sync.py from {source}. Do not edit. -->"]
    lines += ["{% raw %}", "", f"# {title}", "", body.rstrip("\n"), "{% endraw %}", ""]
    return "\n".join(lines)


GENERATED = {
    "docs/prompts/index.md": generated_page(
        "Prompt library", 10, "", "", "prompts", "- [Stage 1 prompts](s1/index.md)\n"
    ),
    "docs/prompts/s1/index.md": generated_page(
        "Stage 1 prompts",
        1,
        "Prompt library",
        "",
        "prompts/s1",
        "- [P-S1-01 Example prompt](p-s1-01.md)\n",
    ),
    "docs/prompts/s1/p-s1-01.md": generated_page(
        "P-S1-01 Example prompt",
        1,
        "Stage 1 prompts",
        "Prompt library",
        "prompts/s1/example.md",
        "| Field | Value |\n|---|---|\n| Needs | `llm` |\n"
        "| Placeholders | `{{TOPIC}}` |\n"
        "| Used in | [S1.1 Example sub-stage](../../s1-1-example.md) |\n"
        "| Source | [example.md](https://example.org/blob/main/example.md) |\n\n"
        "## Prompt\n\n"
        + FENCE4
        + "text\nWrite one sentence about {{TOPIC}}.\n"
        + FENCE4
        + "\n\n## Notes\n\nNotes go here.\n",
    ),
    "docs/scripts/index.md": generated_page(
        "Script library", 11, "", "", "scripts", "- [Stage 1 scripts](s1/index.md)\n"
    ),
    "docs/scripts/s1/index.md": generated_page(
        "Stage 1 scripts",
        1,
        "Script library",
        "",
        "scripts/s1",
        "- [X-S1-01 Example script](x-s1-01.md)\n",
    ),
    "docs/scripts/s1/x-s1-01.md": generated_page(
        "X-S1-01 Example script",
        1,
        "Stage 1 scripts",
        "Script library",
        "scripts/s1/example.py",
        "| Field | Value |\n|---|---|\n| Purpose | Print a greeting. |\n"
        "| Used in | [S1.1 Example sub-stage](../../s1-1-example.md) |\n",
    ),
}

FAKE_SYNC_ECHO = '''"""Fake sync for CLI tests: returns generated files as they are."""

import os


def compute_outputs(root):
    out = {}
    for sub in ("docs/assets/images", "docs/prompts", "docs/scripts"):
        for base, _dirs, files in os.walk(os.path.join(root, *sub.split("/"))):
            for name in files:
                path = os.path.join(base, name)
                rel = os.path.relpath(path, root).replace(os.sep, "/")
                with open(path, "rb") as handle:
                    out[rel] = handle.read()
    return out
'''


def fake_key() -> str:
    return "AK" + "IA" + "ABCDEFGHIJKLMNOP"


def fake_private_key_header() -> str:
    return "-----BEGIN " + "RSA PRIVATE " + "KEY-----"


def user_path() -> str:
    return "/" + "Users" + "/" + "someone" + "/notes"


def home_path() -> str:
    return "/" + "home" + "/" + "someone"


def windows_path() -> str:
    return "C:" + "\\" + "Users" + "\\" + "someone"


def file_url() -> str:
    return "file" + ":" + "///tmp/x"


def foreign_email() -> str:
    return "someone" + "@" + "acme.test"


class Fixture:
    """A small clean repository, built under a temporary directory."""

    def __init__(self, base: Path) -> None:
        self.root = base / "repo"
        self.generated: dict[str, bytes] = {}
        self.write("docs/_config.yml", 'title: "Fixture"\nbaseurl: "/fixture"\n')
        self.write("docs/index.md", HOME)
        self.write("docs/s1-1-example.md", STAGE)
        self.write("docs/_includes/footer_custom.html", FOOTER)
        self.write("images/flow.svg", SVG)
        self.set_generated("docs/assets/images/flow.svg", SVG)
        for rel, text in GENERATED.items():
            self.set_generated(rel, text)
        self.write("prompts/s1/example.md", PROMPT)
        self.write("scripts/s1/example.py", SCRIPT)
        self.write("README.md", "Template file.\n")
        self.write("CONTRIBUTING.md", "Template file.\n")

    def path(self, rel: str) -> Path:
        return self.root / rel

    def write(self, rel: str, text: str) -> Path:
        return self.write_bytes(rel, text.encode("utf-8"))

    def write_bytes(self, rel: str, data: bytes) -> Path:
        path = self.path(rel)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        return path

    def set_generated(self, rel: str, text: str) -> None:
        """Write a generated file and record it as the expected sync output."""
        self.write(rel, text)
        self.generated[rel] = text.encode("utf-8")

    def read(self, rel: str) -> str:
        return self.path(rel).read_bytes().decode("utf-8")

    def edit(self, rel: str, old: str, new: str) -> None:
        text = self.read(rel)
        if old not in text:
            raise AssertionError(f"{old!r} not found in {rel}")
        self.write(rel, text.replace(old, new, 1))

    def line(self, rel: str, needle: str) -> int:
        """1-based number of the first line of the file that holds needle."""
        for number, line in enumerate(self.read(rel).split("\n"), 1):
            if needle in line:
                return number
        raise AssertionError(f"{needle!r} not found in {rel}")

    def append(self, rel: str, text: str) -> int:
        """Append a blank line and text; return the line number of the text."""
        before = self.read(rel)
        self.write(rel, before + "\n" + text + "\n")
        return before.count("\n") + 2

    def remove(self, rel: str) -> None:
        self.path(rel).unlink()


class FakeSync(types.ModuleType):
    """Stands in for sync.py; compute_outputs calls the given provider."""

    def __init__(self, provider: Callable[[], Any]) -> None:
        super().__init__("sync")
        self._provider = provider

    def compute_outputs(self, root: Path) -> Any:
        del root
        return self._provider()


class CheckCase(unittest.TestCase):
    """Builds a clean fixture and a fake sync for every test."""

    def setUp(self) -> None:
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.base = Path(tmp.name)
        self.fx = Fixture(self.base)
        self.install_sync(lambda: dict(self.fx.generated))

    def install_sync(self, provider: Callable[[], Any]) -> None:
        saved = sys.modules.get("sync")
        self.addCleanup(self.restore_sync, saved)
        sys.modules["sync"] = FakeSync(provider)

    @staticmethod
    def restore_sync(saved: types.ModuleType | None) -> None:
        if saved is None:
            sys.modules.pop("sync", None)
        else:
            sys.modules["sync"] = saved

    def findings(self, forbidden: Path | None = None) -> list[sitelib.Finding]:
        return check.run(self.fx.root, forbidden)

    def expect(
        self, *expected: str, forbidden: Path | None = None
    ) -> list[sitelib.Finding]:
        """Assert the exact set of 'SEV path:line RULE' keys; return findings."""
        found = self.findings(forbidden)
        actual = {f"{f.severity} {f.path}:{f.line} {f.rule}" for f in found}
        self.assertEqual(actual, set(expected), "\n".join(map(str, found)))
        return found

    def run_main(
        self, *argv: str, environ: dict[str, str] | None = None
    ) -> tuple[int, str, str]:
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            code = check.main(list(argv), environ={} if environ is None else environ)
        return code, out.getvalue(), err.getvalue()


class CleanFixtureTests(CheckCase):
    def test_clean_fixture_has_no_findings_at_all(self) -> None:
        self.assertEqual([], self.findings())

    def test_clean_fixture_passes_with_a_private_list_that_matches_nothing(
        self,
    ) -> None:
        terms = self.base / "terms.txt"
        terms.write_text(
            "# none of these appear\nre:q[0-9]{12}\nnever-present\n", encoding="utf-8"
        )
        self.assertEqual([], self.findings(terms))

    def test_main_prints_only_the_summary_and_the_notice(self) -> None:
        code, out, err = self.run_main("--root", str(self.fx.root))
        self.assertEqual(code, 0)
        self.assertEqual(out, "check: 0 errors, 0 warnings\n")
        self.assertEqual(err, "R10 private-term check skipped: no list supplied\n")

    def test_clean_fixture_repeats_the_negative_cases(self) -> None:
        # The stage page already holds a link, a "#" heading and Liquid inside
        # a fence and inline code; none of them may be seen outside a raw block.
        text = self.fx.read("docs/s1-1-example.md")
        self.assertIn("# not a heading", text)
        self.assertIn("`[x](missing.md)`", text)
        self.assertEqual([], self.findings())


class FrontMatterTests(CheckCase):
    def test_r01_missing_status(self) -> None:
        self.fx.edit("docs/index.md", 'status: "draft"\n', "")
        self.expect("E docs/index.md:1 R01")

    def test_r01_missing_nav_order_unless_excluded(self) -> None:
        self.fx.edit("docs/index.md", "nav_order: 1\n", "")
        self.expect("E docs/index.md:1 R01")
        self.fx.edit(
            "docs/index.md", 'title: "Home"\n', 'title: "Home"\nnav_exclude: true\n'
        )
        self.expect()

    def test_r01_unquoted_string_is_reported_on_its_line(self) -> None:
        self.fx.edit("docs/index.md", 'title: "Home"', "title: Home")
        self.expect("E docs/index.md:2 R01")

    def test_r01_duplicate_key(self) -> None:
        self.fx.edit("docs/index.md", "nav_order: 1\n", "nav_order: 1\nnav_order: 5\n")
        self.expect("E docs/index.md:4 R01")

    def test_r01_unknown_key_is_a_warning(self) -> None:
        self.fx.edit(
            "docs/index.md", "---\n\n# Fixture", 'colour: "red"\n---\n\n# Fixture'
        )
        self.expect("W docs/index.md:6 R01")

    def test_r01_page_without_front_matter(self) -> None:
        self.fx.write("docs/plain.md", "# Plain\n\n" + "Some words here. " * 20 + "\n")
        self.expect("E docs/plain.md:1 R01")

    def test_r01_title_with_ampersand(self) -> None:
        self.fx.edit("docs/index.md", 'title: "Home"', 'title: "Home & away"')
        self.expect("E docs/index.md:2 R01")

    def test_r01_bad_status_value_and_bad_date(self) -> None:
        self.fx.edit("docs/index.md", 'status: "draft"', 'status: "done"')
        self.expect("E docs/index.md:4 R01")
        self.fx.edit("docs/index.md", 'status: "done"', 'status: "draft"')
        self.fx.edit("docs/index.md", "2026-01-15", "2026-13-45")
        self.expect("E docs/index.md:5 R01")

    def test_r01_wrong_type(self) -> None:
        self.fx.edit("docs/index.md", 'status: "draft"', "status: 3")
        self.expect("E docs/index.md:4 R01")

    def test_r02_duplicate_title_is_reported_on_the_later_page(self) -> None:
        self.fx.edit(
            "docs/s1-1-example.md", 'title: "S1.1 Example sub-stage"', 'title: "Home"'
        )
        self.expect("E docs/s1-1-example.md:2 R02")

    def test_r02_parent_that_matches_no_title(self) -> None:
        self.fx.edit(
            "docs/s1-1-example.md",
            "nav_order: 2\n",
            'nav_order: 2\nparent: "Nowhere"\n',
        )
        self.expect("E docs/s1-1-example.md:4 R02")

    def test_r02_page_cannot_be_its_own_parent(self) -> None:
        self.fx.edit(
            "docs/index.md", "nav_order: 1\n", 'nav_order: 1\nparent: "Home"\n'
        )
        self.expect("E docs/index.md:4 R02")

    def test_r02_wrong_grand_parent(self) -> None:
        rel = "docs/prompts/s1/p-s1-01.md"
        self.fx.set_generated(
            rel,
            self.fx.read(rel).replace(
                'grand_parent: "Prompt library"', 'grand_parent: "Script library"'
            ),
        )
        self.expect("E docs/prompts/s1/p-s1-01.md:4 R02")

    def test_r02_missing_grand_parent_for_a_nested_parent(self) -> None:
        rel = "docs/prompts/s1/p-s1-01.md"
        self.fx.set_generated(
            rel, self.fx.read(rel).replace('grand_parent: "Prompt library"\n', "")
        )
        self.expect("E docs/prompts/s1/p-s1-01.md:3 R02")

    def test_r02_has_children_false_is_forbidden(self) -> None:
        self.fx.edit(
            "docs/index.md", "nav_order: 1\n", "nav_order: 1\nhas_children: false\n"
        )
        self.expect("E docs/index.md:4 R02")
        self.fx.edit("docs/index.md", "has_children: false", "has_children: true")
        self.expect()

    def test_r03_nav_order_must_be_an_integer(self) -> None:
        self.fx.edit("docs/s1-1-example.md", "nav_order: 2", 'nav_order: "2"')
        self.expect("E docs/s1-1-example.md:3 R03")
        self.fx.edit("docs/s1-1-example.md", 'nav_order: "2"', "nav_order: true")
        self.expect("E docs/s1-1-example.md:3 R03")

    def test_r03_nav_order_must_be_unique_among_siblings(self) -> None:
        self.fx.edit("docs/s1-1-example.md", "nav_order: 2", "nav_order: 1")
        self.expect("E docs/s1-1-example.md:3 R03")

    def test_r03_same_number_under_different_parents_is_fine(self) -> None:
        # The fixture already reuses nav_order 1 under different parents.
        self.assertEqual([], self.findings())


class LinkTests(CheckCase):
    PAGE = "docs/s1-1-example.md"

    def plant(self, text: str) -> int:
        return self.fx.append(self.PAGE, text)

    def test_r04_broken_link(self) -> None:
        self.fx.edit(self.PAGE, "[home page](index.md)", "[home page](missing.md)")
        line = self.fx.line(self.PAGE, "[home page](missing.md)")
        self.expect(f"E {self.PAGE}:{line} R04")

    def test_r04_leading_slash_is_an_error(self) -> None:
        line = self.plant("Go to [the home page](/index.md).")
        self.expect(f"E {self.PAGE}:{line} R04")

    def test_r04_leading_slash_on_an_image_is_r04_too(self) -> None:
        line = self.plant("![Flow picture](/assets/images/flow.svg)")
        self.expect(f"E {self.PAGE}:{line} R04")

    def test_r04_letter_case_must_match_exactly(self) -> None:
        line = self.plant("See [the home page](Index.md).")
        self.expect(f"E {self.PAGE}:{line} R04")

    def test_r04_html_anchor_tag(self) -> None:
        line = self.plant('See <a href="missing.md">the missing page</a>.')
        self.expect(f"E {self.PAGE}:{line} R04")

    def test_r04_link_forms_that_resolve(self) -> None:
        self.plant(
            '[a](<index.md>) [b](index.md "The home page") [c](index.md?x=1) '
            "[d](index%2Emd) [e](./index.md) [f](../docs/index.md) [g](prompts/)\n\n"
            "[h][home] and [i][] and <a href='index.md'>the home page</a>\n\n"
            "[home]: index.md\n[i]: <index.md> 'Title'\n"
        )
        self.expect()

    def test_r04_broken_forms(self) -> None:
        a = self.plant('[a](<nope-a.md> "title")')
        b = self.plant("[b](nope-b.md#top)")
        c = self.plant("[c][nolabel]")
        d = self.plant("[c]: nope-d.md")
        e = self.plant("[e]()")
        self.expect(*(f"E {self.PAGE}:{n} R04" for n in (a, b, c, d, e)))

    def test_r04_external_and_liquid_targets_are_not_resolved(self) -> None:
        self.plant(
            "[a](https://example.org/nope) [b](mailto:x@example.org) "
            "[c](//example.org/x) [d]({{ '/x/' | relative_url }}) [e](#)"
        )
        self.expect()

    def test_r04_masked_text_raises_nothing(self) -> None:
        self.plant(
            "Inline `[a](gone.md)` and `# b` are code.\n\n<!-- [c](gone.md) -->\n\n"
            + FENCE3
            + "text\n[d](gone.md)\n# e\n### f\n"
            + FENCE3
        )
        self.expect()

    def test_r04_nested_image_link(self) -> None:
        line = self.plant("[![Flow diagram](assets/images/flow.svg)](missing.md)")
        self.expect(f"E {self.PAGE}:{line} R04")

    def test_r04a_missing_anchor_on_a_plain_heading(self) -> None:
        a = self.plant("[a](#no-such-heading)")
        b = self.plant("[b](index.md#nope)")
        self.expect(f"E {self.PAGE}:{a} R04a", f"E {self.PAGE}:{b} R04a")

    def test_r04a_uncertain_heading_is_a_warning(self) -> None:
        self.plant("## The `foo` step")
        a = self.plant("[a](#the--step)")
        b = self.plant("[b](#the-foo-step)")
        c = self.plant("[c](#the-bar-step)")
        self.expect(
            f"W {self.PAGE}:{a} R04a",
            f"W {self.PAGE}:{b} R04a",
            f"E {self.PAGE}:{c} R04a",
        )

    def test_r04a_non_ascii_heading_is_a_warning(self) -> None:
        self.plant("## Caf\u00e9 notes")
        line = self.plant("[a](#caf\u00e9-notes)")
        self.expect(f"W {self.PAGE}:{line} R04a")

    def test_r04a_explicit_id_and_html_anchor_are_exact(self) -> None:
        self.plant("## Odd `x` {#odd-x}")
        self.plant('<a id="custom-anchor"></a>')
        self.plant("[a](#odd-x) [b](#custom-anchor)")
        self.expect()

    def test_r04a_duplicate_headings_get_numbered_ids(self) -> None:
        first = self.plant("## Extra\n\ntext\n\n## Extra")
        self.plant("[a](#extra) [b](#extra-1)")
        self.expect(f"W {self.PAGE}:{first + 4} R20")

    def test_r05_target_outside_docs(self) -> None:
        a = self.plant("[a](../README.md)")
        b = self.plant("![Flow picture](../images/flow.svg)")
        c = self.plant("[c](../nothing-here.md)")
        self.expect(
            f"E {self.PAGE}:{a} R05", f"E {self.PAGE}:{b} R05", f"E {self.PAGE}:{c} R04"
        )

    def test_r06_missing_image_file(self) -> None:
        line = self.plant("![Flow picture](assets/images/nope.svg)")
        self.expect(f"E {self.PAGE}:{line} R06")

    def test_r06_empty_and_missing_alt_text(self) -> None:
        a = self.plant("![](assets/images/flow.svg)")
        b = self.plant('<img src="assets/images/flow.svg">')
        c = self.plant('<img src="assets/images/flow.svg" alt="">')
        d = self.plant('<img src="assets/images/flow.svg" alt="Flow picture">')
        found = self.expect(*(f"E {self.PAGE}:{n} R06" for n in (a, b, c)))
        self.assertNotIn(d, {f.line for f in found})


class SourceFileTests(CheckCase):
    PROMPT = "prompts/s1/example.md"
    SCRIPT = "scripts/s1/example.py"
    STAGE = "docs/s1-1-example.md"

    def test_r07_duplicate_id_is_reported_on_the_second_file(self) -> None:
        self.fx.write("prompts/s1/second.md", PROMPT)
        self.expect("E prompts/s1/second.md:2 R07")

    def test_r07_folder_must_match_the_id_code(self) -> None:
        self.fx.remove(self.PROMPT)
        self.fx.write("prompts/s2/example.md", PROMPT)
        self.expect("E prompts/s2/example.md:2 R07")

    def test_r07_stage_must_match_the_id_code(self) -> None:
        self.fx.edit(self.PROMPT, 'stage: "S1"', 'stage: "S2"')
        self.expect("E prompts/s1/example.md:4 R07")

    def test_r07_file_name_must_be_a_slug(self) -> None:
        self.fx.remove(self.PROMPT)
        self.fx.write("prompts/s1/Bad Name.md", PROMPT)
        self.expect("E prompts/s1/Bad Name.md:1 R07")

    def test_r07_id_shape(self) -> None:
        self.fx.edit(self.PROMPT, 'id: "P-S1-01"', 'id: "P-S1-1"')
        self.expect("E prompts/s1/example.md:2 R07", f"E {self.STAGE}:8 R07")

    def test_r07_script_stage_field_must_agree(self) -> None:
        self.fx.edit(self.SCRIPT, "Stage: S1", "Stage: S2")
        line = self.fx.line(self.SCRIPT, "Stage:")
        self.expect(f"E scripts/s1/example.py:{line} R07")

    def test_r07_script_folder_and_common(self) -> None:
        self.fx.remove(self.SCRIPT)
        self.fx.write("scripts/common/example.py", SCRIPT)
        line = self.fx.line("scripts/common/example.py", "ID:")
        self.expect(f"E scripts/common/example.py:{line} R07")

    def test_r07_listed_id_must_exist(self) -> None:
        self.fx.edit(self.STAGE, 'prompts: ["P-S1-01"]', 'prompts: ["P-S1-09"]')
        self.expect(f"E {self.STAGE}:8 R07")

    def test_r07_page_stage_must_agree_with_listed_items(self) -> None:
        self.fx.edit(self.STAGE, 'stage: "S1"', 'stage: "S2"')
        self.fx.edit(self.STAGE, 'sub_stage: "S1.1"', 'sub_stage: "S2.1"')
        self.expect(f"E {self.STAGE}:8 R07", f"E {self.STAGE}:9 R07")

    def test_r07_op_items_may_be_listed_by_any_stage_page(self) -> None:
        self.fx.remove(self.SCRIPT)
        self.fx.write("scripts/common/example.py", SCRIPT.replace("S1", "OP"))
        self.fx.edit(self.STAGE, 'scripts: ["X-S1-01"]', 'scripts: ["X-OP-01"]')
        self.fx.edit(self.STAGE, "scripts/s1/x-s1-01.md", "scripts/op/x-op-01.md")
        self.expect(f"E {self.STAGE}:{self.fx.line(self.STAGE, 'x-op-01')} R04")

    def test_r07_bad_sub_stage(self) -> None:
        self.fx.edit(self.STAGE, 'sub_stage: "S1.1"', 'sub_stage: "S2.1"')
        self.expect(f"E {self.STAGE}:7 R07")

    def test_r08_placeholder_used_but_not_declared(self) -> None:
        self.fx.edit(self.PROMPT, "{{TOPIC}}.", "{{TOPIC}} and {{OTHER}}.")
        self.expect(f"E {self.PROMPT}:{self.fx.line(self.PROMPT, 'placeholders:')} R08")

    def test_r08_placeholder_declared_but_not_used(self) -> None:
        self.fx.edit(self.PROMPT, '["TOPIC"]', '["TOPIC", "UNUSED"]')
        self.expect(f"E {self.PROMPT}:{self.fx.line(self.PROMPT, 'placeholders:')} R08")

    def test_r08_capability_outside_the_vocabulary(self) -> None:
        self.fx.edit(self.PROMPT, '["llm"]', '["llm", "telepathy"]')
        self.expect(f"E {self.PROMPT}:{self.fx.line(self.PROMPT, 'capabilities:')} R08")

    def test_r08_second_prompt_fence(self) -> None:
        line = self.fx.append(self.PROMPT, FENCE4 + "text\nAnother.\n" + FENCE4)
        self.expect(f"E {self.PROMPT}:{line} R08")

    def test_r08_raw_closing_tag_in_the_file(self) -> None:
        line = self.fx.append(self.PROMPT, "The tag {% endraw %} would end the block.")
        self.expect(f"E {self.PROMPT}:{line} R08")

    def test_r08_missing_required_key(self) -> None:
        self.fx.edit(self.PROMPT, 'purpose: "Show how a prompt file looks."\n', "")
        self.expect("E prompts/s1/example.md:1 R08")

    def test_r08_unknown_key_is_a_warning(self) -> None:
        self.fx.edit(
            self.PROMPT,
            'capabilities: ["llm"]\n',
            'capabilities: ["llm"]\ncolour: "red"\n',
        )
        self.expect(f"W {self.PROMPT}:{self.fx.line(self.PROMPT, 'colour:')} R08")

    def test_r09_missing_required_field(self) -> None:
        self.fx.edit(self.SCRIPT, "Usage: python3 scripts/s1/example.py\n", "")
        self.expect("E scripts/s1/example.py:1 R09")

    def test_r09_import_that_is_not_declared(self) -> None:
        self.fx.edit(
            self.SCRIPT, 'print("hello")', "import requests\n\nprint(requests)"
        )
        line = self.fx.line(self.SCRIPT, "Dependencies:")
        self.expect(f"E scripts/s1/example.py:{line} R09")
        self.fx.edit(self.SCRIPT, "Dependencies: stdlib", "Dependencies: requests")
        self.expect()

    def test_r09_key_pattern_in_a_script_is_r09_not_r10(self) -> None:
        line = self.fx.append(self.SCRIPT, 'TOKEN = "' + fake_key() + '"')
        found = self.expect(f"E scripts/s1/example.py:{line} R09")
        self.assertNotIn(fake_key(), str(found[0]))

    def test_r09_license_must_be_cc0(self) -> None:
        self.fx.edit(self.SCRIPT, "License: CC0-1.0", "License: MIT")
        self.expect(
            f"E scripts/s1/example.py:{self.fx.line(self.SCRIPT, 'License:')} R09"
        )

    def test_readme_files_and_test_files_are_not_library_sources(self) -> None:
        self.fx.write("prompts/s1/README.md", "# Notes\n")
        self.fx.write("prompts/s1/_draft.md", "no front matter\n")
        self.fx.write("scripts/s1/test_example.py", "print('x')\n")
        self.fx.write("scripts/s1/__init__.py", "")
        self.fx.write("prompts/README.md", "# Prompts\n")
        self.expect()

    def test_r21_listed_id_without_a_link(self) -> None:
        self.fx.edit(
            self.STAGE, "[P-S1-01 Example prompt](prompts/s1/p-s1-01.md)", "P-S1-01"
        )
        self.expect(f"W {self.STAGE}:8 R21")

    def test_r21_sections_out_of_order(self) -> None:
        self.fx.edit(
            self.STAGE,
            PROMPTS_SECTION + SCRIPTS_SECTION,
            SCRIPTS_SECTION + PROMPTS_SECTION,
        )
        self.expect(f"W {self.STAGE}:{self.fx.line(self.STAGE, '## Prompts')} R21")

    def test_r21_only_pages_with_stage_and_sub_stage_are_ordered(self) -> None:
        self.fx.append(
            "docs/index.md", "## Scripts\n\nSome text.\n\n## Prompts\n\nMore text."
        )
        self.expect()


class RawTextRuleTests(CheckCase):
    PAGE = "docs/s1-1-example.md"

    def plant(self, text: str) -> int:
        return self.fx.append(self.PAGE, text)

    def test_r10_public_constants(self) -> None:
        samples = {
            "macOS path": user_path(),
            "Linux path": home_path(),
            "Windows path": windows_path(),
            "file URL": file_url(),
            "email": foreign_email(),
            "key": fake_key(),
            "private key": fake_private_key_header(),
        }
        for name, sample in samples.items():
            with self.subTest(name):
                rel = "docs/index.md"
                self.fx.write(rel, HOME)
                line = self.fx.append(rel, "Note: " + sample + " end")
                found = self.expect(f"E {rel}:{line} R10")
                for finding in found:
                    self.assertNotIn(sample, str(finding))
                    self.assertNotIn("someone", str(finding))

    def test_r10_reads_code_blocks_and_all_scanned_folders(self) -> None:
        line = self.plant(FENCE3 + "text\n" + user_path() + "\n" + FENCE3)
        self.fx.write("images/notes.txt", "x\n" + home_path() + "\n")
        self.fx.write("scripts/sample_data/x.json", '{"k": "' + fake_key() + '"}\n')
        self.expect(
            f"E {self.PAGE}:{line + 1} R10",
            "E images/notes.txt:2 R10",
            "E scripts/sample_data/x.json:1 R10",
        )

    def test_r10_allowed_email_addresses(self) -> None:
        self.plant("a@example.com, b@mail.example.org, c@example.net, git@github.com")
        self.expect()

    def test_r10_skips_this_tool_the_tests_and_repo_root_files(self) -> None:
        bad = user_path() + " " + fake_key() + " " + foreign_email() + "\n"
        self.fx.write("scripts/site/check.py", '"""x"""\n# ' + bad)
        self.fx.write("scripts/tests/note.py", "# " + bad)
        self.fx.write("README.md", bad)
        self.fx.write("CONTRIBUTING.md", bad)
        self.fx.write("notes/other.md", bad)
        self.fx.write("docs/Gemfile", bad)
        self.expect()

    def test_r10_private_terms_are_found_and_never_printed(self) -> None:
        term = "zq" + "xv" + "plum"
        terms = self.base / "terms.txt"
        terms.write_text(
            "# comment\n\nre:no[m]atch[0-9]{9}\n" + term + "\nre:qq[0-9]{3}wz\n",
            encoding="utf-8",
        )
        first = self.plant("Notes about " + term.upper() + " appear here.")
        second = self.plant("The code is " + "QQ" + "123" + "WZ" + " today.")
        both = self.plant("Both " + term + " and QQ999WZ appear.")
        found = self.expect(
            f"E {self.PAGE}:{first} R10",
            f"E {self.PAGE}:{second} R10",
            f"E {self.PAGE}:{both} R10",
            forbidden=terms,
        )
        lines = {str(f) for f in found}
        self.assertIn(f"{self.PAGE}:{first} R10 private-term #2", lines)
        self.assertIn(f"{self.PAGE}:{second} R10 private-term #3", lines)
        self.assertIn(f"{self.PAGE}:{both} R10 private-term #2", lines)
        self.assertIn(f"{self.PAGE}:{both} R10 private-term #3", lines)
        code, out, err = self.run_main(
            "--root", str(self.fx.root), "--extra-forbidden", str(terms)
        )
        self.assertEqual(code, 1)
        shown = (out + err).lower()
        for hidden in (term, "zqxv", "plum", "notes about", "qq123", "wz today"):
            self.assertNotIn(hidden, shown)
        self.assertEqual(err, "")

    def test_r10_notice_only_when_no_list_is_supplied(self) -> None:
        root = str(self.fx.root)
        notice = "R10 private-term check skipped: no list supplied\n"
        self.assertEqual(self.run_main("--root", root)[2], notice)
        terms = self.base / "terms.txt"
        terms.write_text("never-present\n", encoding="utf-8")
        self.assertEqual(
            self.run_main("--root", root, "--extra-forbidden", str(terms))[2], ""
        )
        env = {check.FORBIDDEN_ENV: str(terms)}
        self.assertEqual(self.run_main("--root", root, environ=env)[2], "")
        self.assertEqual(
            self.run_main("--root", root, environ={check.FORBIDDEN_ENV: ""})[2], notice
        )

    def test_r10_flag_wins_over_the_environment_variable(self) -> None:
        term = "ab" + "cd" + "efgh"
        line = self.plant("Contains " + term + " here.")
        matching = self.base / "a.txt"
        matching.write_text(term + "\n", encoding="utf-8")
        other = self.base / "b.txt"
        other.write_text("never-present\n", encoding="utf-8")
        root = str(self.fx.root)
        env = {check.FORBIDDEN_ENV: str(matching)}
        code, out, _ = self.run_main("--root", root, environ=env)
        self.assertEqual(code, 1)
        self.assertIn(f"{self.PAGE}:{line} R10 private-term #1", out)
        code, out, err = self.run_main(
            "--root", root, "--extra-forbidden", str(other), environ=env
        )
        self.assertEqual((code, err), (0, ""))

    def test_r10_bad_lists_are_input_errors_that_never_quote_a_term(self) -> None:
        root = str(self.fx.root)
        secret = "sec" + "ret" + "value"
        cases = {
            "invalid regex": "ok\nre:(" + secret + "\n",
            "empty regex": "re:(" + secret + ")?\n",
        }
        bad = self.base / "bad.txt"
        for name, content in cases.items():
            with self.subTest(name):
                bad.write_text(content, encoding="utf-8")
                code, out, err = self.run_main(
                    "--root", root, "--extra-forbidden", str(bad)
                )
                self.assertEqual((code, out), (2, ""))
                self.assertIn("private term #", err)
                self.assertNotIn(secret, err)
        missing = self.base / "missing.txt"
        code, out, err = self.run_main(
            "--root", root, "--extra-forbidden", str(missing)
        )
        self.assertEqual((code, out), (2, ""))
        self.assertIn("private term list", err)
        bad.write_bytes(b"\xff\xfe")
        code, _, _ = self.run_main("--root", root, "--extra-forbidden", str(bad))
        self.assertEqual(code, 2)

    def test_r16_liquid_outside_a_raw_block(self) -> None:
        a = self.plant("Use {{NAME}} in a sentence.")
        b = self.plant("A tag {% if x %} in text.")
        self.expect(f"E {self.PAGE}:{a} R16", f"E {self.PAGE}:{b} R16")

    def test_r16_fences_inline_code_and_comments_are_not_exempt(self) -> None:
        text = (
            FENCE3 + "text\nfirst {{NAME}}\n" + FENCE3 + "\n\nInline `{{X}}` here.\n\n"
            "<!-- {{Z}} -->"
        )
        line = self.plant(text)
        self.expect(
            f"E {self.PAGE}:{line + 1} R16",
            f"E {self.PAGE}:{line + 4} R16",
            f"E {self.PAGE}:{line + 6} R16",
        )

    def test_r16_allowed_forms_and_raw_blocks(self) -> None:
        self.plant(
            "A {{ 'x' | relative_url }} and {{ \"/y/\" | relative_url }}.\n\n"
            "A {% link s1-1-example.md %} and {% link a.md %}.\n\n"
            "[go]({{ '/z/' | relative_url }})\n\n"
            "{% raw %}{{NAME}} and {% if %}{% endraw %} plus {% raw %}{{X}}{% endraw %}"
        )
        self.expect()

    def test_r16_endraw_without_raw(self) -> None:
        line = self.plant("{% endraw %}")
        self.expect(f"E {self.PAGE}:{line} R16")

    def test_r16_raw_that_is_never_closed(self) -> None:
        line = self.plant("{% raw %}\nNever closed {{NAME}}.")
        self.expect(f"E {self.PAGE}:{line} R16")

    def test_r16_also_covers_generated_pages(self) -> None:
        rel = "docs/prompts/s1/p-s1-01.md"
        text = self.fx.read(rel)
        self.fx.write(rel, text + "\nStray {{X}} outside the block.\n")
        line = self.fx.line(rel, "Stray")
        self.expect(f"E {rel}:{line} R16", f"E {rel}:1 R11")

    def test_r17_carriage_return_and_bom(self) -> None:
        data = self.fx.path("docs/index.md").read_bytes().replace(b"\n", b"\r\n")
        self.fx.write_bytes("docs/index.md", data)
        self.expect("E docs/index.md:1 R17")
        self.fx.write("docs/index.md", HOME)
        self.fx.write_bytes("prompts/s1/example.md", b"\xef\xbb\xbf" + PROMPT.encode())
        found = self.expect("E prompts/s1/example.md:1 R17")
        self.assertIn("byte order mark", found[0].message)

    def test_r17_reports_the_line_of_the_first_carriage_return(self) -> None:
        self.fx.write_bytes("docs/assets/x.txt", b"one\ntwo\r\nthree\n")
        self.expect("E docs/assets/x.txt:2 R17")

    def test_r22_root_relative_url_in_an_include(self) -> None:
        self.fx.write(
            "docs/_includes/head_custom.html",
            '<link rel="stylesheet" href="/assets/css/x.css">\n'
            '<script src="/a.js"></script>\n'
            '<link href="{{ \'/ok.css\' | relative_url }}" rel="stylesheet">\n'
            '<a href="//cdn.example.org/x">x</a> <a href="https://example.org/">y</a>\n'
            '<!-- <a href="/commented-out"> -->\n'
            '<a href="page.html">z</a>\n',
        )
        self.expect(
            "E docs/_includes/head_custom.html:1 R22",
            "E docs/_includes/head_custom.html:2 R22",
        )


class TreeTests(CheckCase):
    def test_r11_drifted_file(self) -> None:
        rel = "docs/prompts/s1/p-s1-01.md"
        self.fx.write(rel, self.fx.read(rel) + "\nExtra line.\n")
        self.expect(f"E {rel}:1 R11")

    def test_r11_stale_files(self) -> None:
        self.fx.write_bytes("docs/assets/images/old.png", b"\x89PNG")
        old = generated_page(
            "X-S1-99 Old",
            9,
            "Stage 1 scripts",
            "Script library",
            "scripts/s1/old.py",
            "Old.\n",
        )
        self.fx.write("docs/scripts/s1/old.md", old)
        self.expect(
            "E docs/assets/images/old.png:1 R11", "E docs/scripts/s1/old.md:1 R11"
        )

    def test_r11_missing_generated_file(self) -> None:
        self.fx.remove("docs/assets/images/flow.svg")
        line = self.fx.line("docs/s1-1-example.md", "flow.svg")
        self.expect(
            "E docs/assets/images/flow.svg:1 R11", f"E docs/s1-1-example.md:{line} R06"
        )

    def test_r11_sync_that_raises_is_one_line_and_other_rules_still_run(self) -> None:
        def boom() -> Any:
            raise RuntimeError("sync exploded")

        self.install_sync(boom)
        self.fx.edit("docs/index.md", 'status: "draft"\n', "")
        found = self.expect("E docs/index.md:1 R01", "E scripts/site/sync.py:1 R11")
        self.assertTrue(any("sync exploded" in f.message for f in found))

    def test_r11_sync_that_cannot_be_imported(self) -> None:
        saved = sys.modules.get("sync")
        self.addCleanup(self.restore_sync, saved)
        sys.modules["sync"] = None  # type: ignore[assignment]
        self.expect("E scripts/site/sync.py:1 R11")

    def test_r11_unusable_sync_results(self) -> None:
        good = dict(self.fx.generated)
        self.install_sync(lambda: {**good, "docs/other/x.md": b""})
        self.expect("E scripts/site/sync.py:1 R11")
        self.install_sync(lambda: [])
        self.expect("E scripts/site/sync.py:1 R11")
        self.install_sync(lambda: {**good, "docs/prompts/../x.md": b""})
        self.expect("E scripts/site/sync.py:1 R11")

    def test_r18_symlinks_under_docs(self) -> None:
        outside = self.base / "outside"
        outside.mkdir()
        (outside / "file.txt").write_text("text\n", encoding="utf-8")
        try:
            os.symlink(outside, self.fx.path("docs/linked"), target_is_directory=True)
            os.symlink(outside / "file.txt", self.fx.path("docs/notes.txt"))
        except (OSError, NotImplementedError) as exc:
            self.skipTest(f"symlinks are not available: {exc}")
        self.expect("E docs/linked:1 R18", "E docs/notes.txt:1 R18")

    def test_r18_case_clashes(self) -> None:
        self.assertEqual(
            check.casefold_clashes(["a.md", "A.md", "b.md", "Straße", "STRASSE"]),
            [("a.md", ["A.md", "a.md"]), ("strasse", ["STRASSE", "Straße"])],
        )
        self.assertEqual(check.casefold_clashes(["a", "b"]), [])

    def test_r18_case_clashes_on_a_case_sensitive_file_system(self) -> None:
        self.fx.write("docs/assets/Extra.txt", "one\n")
        self.fx.write("docs/assets/extra.txt", "two\n")
        if len(os.listdir(self.fx.path("docs/assets"))) < 3:
            self.skipTest("the file system ignores letter case")
        self.expect("E docs/assets/Extra.txt:1 R18", "E docs/assets/extra.txt:1 R18")


class StyleTests(CheckCase):
    PAGE = "docs/s1-1-example.md"

    def plant(self, text: str) -> int:
        return self.fx.append(self.PAGE, text)

    def new_page(
        self, rel: str, title: str, nav: int, body: str, status: str = "draft"
    ) -> None:
        front = f'---\ntitle: "{title}"\nnav_order: {nav}\nstatus: "{status}"\n'
        self.fx.write(rel, front + 'last_reviewed: "2026-01-15"\n---\n\n' + body)

    def test_r12_heading_levels_skip(self) -> None:
        line = self.plant("#### Too deep")
        self.expect(f"W {self.PAGE}:{line} R12")

    def test_r12_second_h1(self) -> None:
        line = self.plant("# Second title")
        self.expect(f"W {self.PAGE}:{line} R12")

    def test_r13_fence_without_language(self) -> None:
        line = self.plant(FENCE3 + "\nplain\n" + FENCE3)
        self.expect(f"W {self.PAGE}:{line} R13")

    def test_r13_link_text_here(self) -> None:
        a = self.plant("[here](index.md)")
        b = self.plant("[Click here](index.md).")
        self.plant("[the home page](index.md)")
        self.expect(f"W {self.PAGE}:{a} R13", f"W {self.PAGE}:{b} R13")

    def test_r14_page_over_2500_words(self) -> None:
        self.plant("This is a short sentence. " * 520)
        self.expect(f"W {self.PAGE}:1 R14")

    def test_r14_more_than_ten_percent_long_sentences(self) -> None:
        short = "This sentence is short. " * 8
        long_sentence = (
            "This sentence keeps going " + "and going " * 20 + "until it ends."
        )
        body = (
            "# Long\n\n"
            + short
            + "\n\n"
            + long_sentence
            + "\n\n"
            + long_sentence
            + "\n"
        )
        self.new_page("docs/long.md", "Long", 5, body)
        self.expect(f"W docs/long.md:{self.fx.line('docs/long.md', 'keeps going')} R14")

    def test_r14_one_long_sentence_in_eleven_is_fine(self) -> None:
        short = "This sentence is short. " * 10
        long_sentence = (
            "This sentence keeps going " + "and going " * 20 + "until it ends."
        )
        self.new_page(
            "docs/long.md", "Long", 5, "# Long\n\n" + short + long_sentence + "\n"
        )
        self.expect()

    def test_r15_unfinished_marker_needs_a_draft_status(self) -> None:
        line = self.plant("TODO finish this sentence.")
        self.expect()
        self.plant("A todo in lower case is not a marker.")
        self.fx.edit(self.PAGE, 'status: "draft"', 'status: "reviewed"')
        self.expect(f"W {self.PAGE}:{line} R15")
        self.fx.edit(self.PAGE, "TODO finish", "FIXME finish")
        self.expect(f"W {self.PAGE}:{line} R15")

    def test_r19_short_page_and_page_without_h1(self) -> None:
        self.new_page("docs/short.md", "Short", 5, "# Short\n\nOnly a few words.\n")
        self.new_page("docs/flat.md", "Flat", 6, "Some words. " * 40 + "\n")
        self.expect("W docs/short.md:1 R19", "W docs/flat.md:1 R19")

    def test_r20_duplicate_heading_text(self) -> None:
        self.plant("## Extras\n\nText.")
        line = self.plant("## Extras\n\nMore text.")
        self.expect(f"W {self.PAGE}:{line} R20")

    def test_generated_pages_skip_style_warnings(self) -> None:
        rel = "docs/prompts/s1/p-s1-01.md"
        text = self.fx.read(rel).replace("Notes go here.", "TODO Notes go here.")
        self.fx.set_generated(rel, text)
        self.expect()

    def test_warnings_never_change_the_exit_code(self) -> None:
        self.plant("#### Too deep")
        code, out, _ = self.run_main("--root", str(self.fx.root))
        self.assertEqual(code, 0)
        self.assertTrue(out.endswith("check: 0 errors, 1 warnings\n"))


class HelperTests(unittest.TestCase):
    def test_strip_raw_keeps_length_and_newlines(self) -> None:
        text = "a {% raw %}{{x}}\n{% endraw %} b {{y}}\nc"
        stripped, problems = check.strip_raw(text)
        self.assertEqual(problems, [])
        self.assertEqual(len(stripped), len(text))
        self.assertEqual(stripped.count("\n"), text.count("\n"))
        self.assertNotIn("{{x}}", stripped)
        self.assertIn("{{y}}", stripped)

    def test_raw_inside_raw_is_literal_text(self) -> None:
        stripped, problems = check.strip_raw("{% raw %} {% raw %} {{x}} {% endraw %} z")
        self.assertEqual(problems, [])
        self.assertNotIn("{{", stripped)

    def test_email_search_matches_the_shared_pattern(self) -> None:
        samples = [  # "#" stands for the at sign, so no address sits in this file
            "a#example.com",
            "x a.b#c.de, y#z.org. and mail:John.Doe+tag#sub.example.co.uk!",
            "#handle a# ## a#b a#b.c no email at all",
            "two: p#one.io q#two.io",
        ]
        for line in (sample.replace("#", "@") for sample in samples):
            with self.subTest(line=line):
                expected = [m.group() for m in sitelib.EMAIL_RE.finditer(line)]
                self.assertEqual(check.emails(line), expected)

    def test_very_long_lines_stay_fast(self) -> None:
        started = time.perf_counter()
        for line in ("a" * 300000, "a" * 300000 + "@", "a@" * 100000):
            check.public_hits(line, True)
        self.assertLess(time.perf_counter() - started, 10)

    def test_sources_are_clean_for_the_public_scan(self) -> None:
        needles = ["/Us" + "ers/", "/ho" + "me/", "C:\\Us" + "ers\\", "file:" + "///"]
        for path in (SITE_DIR / "check.py", Path(__file__)):
            text = path.read_text(encoding="utf-8")
            with self.subTest(file=path.name):
                for pattern in sitelib.SECRET_PATTERNS:
                    self.assertIsNone(pattern.search(text), pattern.pattern)
                for match in sitelib.EMAIL_RE.finditer(text):
                    self.assertTrue(sitelib.email_allowed(match.group()), match.group())
                for needle in needles:
                    self.assertNotIn(needle, text)
                self.assertIn("CC0-1.0", text)


class CliTests(unittest.TestCase):
    """Runs a copy of the tool beside a fake sync.py, so exit codes are exact."""

    def setUp(self) -> None:
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.base = Path(tmp.name)
        self.fx = Fixture(self.base)
        self.tool = self.base / "tool"
        self.tool.mkdir()
        for name in ("check.py", "sitelib.py"):
            shutil.copy2(SITE_DIR / name, self.tool / name)
        (self.tool / "sync.py").write_text(FAKE_SYNC_ECHO, encoding="utf-8")

    def cli(
        self, *args: str, script: Path | None = None, env: dict[str, str] | None = None
    ) -> "subprocess.CompletedProcess[str]":
        environ = {k: v for k, v in os.environ.items() if k != check.FORBIDDEN_ENV}
        environ["PYTHONDONTWRITEBYTECODE"] = "1"
        environ.update(env or {})
        command = [sys.executable, "-B", str(script or self.tool / "check.py"), *args]
        return subprocess.run(  # nosec B603
            command,
            capture_output=True,
            text=True,
            check=False,
            env=environ,
            cwd=self.base,
        )

    def test_exit_0_on_a_clean_repository(self) -> None:
        done = self.cli("--root", str(self.fx.root))
        self.assertEqual(done.returncode, 0, done.stdout + done.stderr)
        self.assertEqual(done.stdout, "check: 0 errors, 0 warnings\n")
        self.assertEqual(done.stderr, check.NOTICE + "\n")

    def test_exit_1_on_an_error_and_lines_are_sorted(self) -> None:
        self.fx.edit("docs/index.md", 'status: "draft"\n', "")
        self.fx.append("docs/s1-1-example.md", "[a](missing.md)")
        self.fx.append("docs/s1-1-example.md", "Path " + user_path())
        done = self.cli("--root", str(self.fx.root))
        self.assertEqual(done.returncode, 1)
        lines = done.stdout.splitlines()
        self.assertEqual(lines[-1], "check: 3 errors, 0 warnings")
        keys = []
        for text in lines[:-1]:
            location, rule = text.split(" ")[:2]
            path, _, number = location.rpartition(":")
            keys.append((path, int(number), rule))
        self.assertEqual(keys, sorted(keys))
        self.assertEqual([k[2] for k in keys], ["R01", "R04", "R10"])

    def test_exit_0_with_warnings_only(self) -> None:
        self.fx.append("docs/s1-1-example.md", "#### Too deep")
        done = self.cli("--root", str(self.fx.root))
        self.assertEqual(done.returncode, 0)
        self.assertTrue(done.stdout.endswith("check: 0 errors, 1 warnings\n"))

    def test_exit_2_for_a_bad_root(self) -> None:
        done = self.cli("--root", str(self.base / "nowhere"))
        self.assertEqual((done.returncode, done.stdout), (2, ""))
        self.assertIn("check:", done.stderr)
        empty = self.base / "empty"
        empty.mkdir()
        self.assertEqual(self.cli("--root", str(empty)).returncode, 2)

    def test_exit_2_for_an_unreadable_list(self) -> None:
        done = self.cli(
            "--root", str(self.fx.root), "--extra-forbidden", str(self.base / "no.txt")
        )
        self.assertEqual((done.returncode, done.stdout), (2, ""))
        self.assertNotIn(check.NOTICE, done.stderr)

    def test_exit_2_for_unknown_options(self) -> None:
        self.assertEqual(self.cli("--nope").returncode, 2)

    def test_exit_2_for_a_page_that_is_not_utf8(self) -> None:
        self.fx.write_bytes("docs/bad.md", b"\xff\xfe not text")
        done = self.cli("--root", str(self.fx.root))
        self.assertEqual((done.returncode, done.stdout), (2, ""))
        self.assertIn("docs/bad.md", done.stderr)

    def test_private_terms_through_the_command_line(self) -> None:
        term = "zq" + "xv" + "plum"
        line = self.fx.append("docs/index.md", "About " + term + " here.")
        terms = self.base / "terms.txt"
        terms.write_text(term + "\n", encoding="utf-8")
        done = self.cli("--root", str(self.fx.root), "--extra-forbidden", str(terms))
        self.assertEqual(done.returncode, 1)
        self.assertIn(f"docs/index.md:{line} R10 private-term #1", done.stdout)
        self.assertNotIn(term, done.stdout + done.stderr)
        self.assertEqual(done.stderr, "")
        env = {check.FORBIDDEN_ENV: str(terms)}
        done = self.cli("--root", str(self.fx.root), env=env)
        self.assertEqual(done.returncode, 1)
        self.assertNotIn(term, done.stdout + done.stderr)

    def test_help_runs_from_the_real_tool(self) -> None:
        done = self.cli("--help", script=SITE_DIR / "check.py")
        self.assertEqual(done.returncode, 0)
        self.assertIn("--extra-forbidden", done.stdout)
        self.assertIn("--root", done.stdout)


if __name__ == "__main__":
    unittest.main()
